// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: adventure.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.adventure
{
    [ProtoBuf.ProtoContract]
    public class I_ADVENTURE_ISLAND_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint mapId;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] clearObjectIds;

        [ProtoBuf.ProtoMember(3)]
        public uint unlockTime;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> rewards = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(5, IsPacked = true)]
        public int[] progressRewards;

    }

    [ProtoBuf.ProtoContract]
    public class I_ADVENTURE_TOUR_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> waitSettleRewards = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint level;

        [ProtoBuf.ProtoMember(3)]
        public uint startTime;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] events;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ADVENTURE_ISLAND_VO> adventureIsland = new System.Collections.Generic.List<I_ADVENTURE_ISLAND_VO>();

        [ProtoBuf.ProtoMember(2)]
        public I_ADVENTURE_TOUR_VO adventureTour;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_CLEAR_OBSTACLE
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong objectId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_CLEAR_OBSTACLE
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong objectId;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public I_ADVENTURE_ISLAND_VO adventureIsland;

        [ProtoBuf.ProtoMember(4)]
        public I_ADVENTURE_TOUR_VO adventureTour;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_STAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong objectId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_STAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong objectId;

        [ProtoBuf.ProtoMember(2)]
        public protobuf.fight.I_BATTLE_PLAYER_VO me;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<protobuf.fight.I_BATTLE_ROUND_VO> roundDetails = new System.Collections.Generic.List<protobuf.fight.I_BATTLE_ROUND_VO>();

        [ProtoBuf.ProtoMember(5)]
        public bool isWin;

        [ProtoBuf.ProtoMember(6)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_PROGRESS_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint mapId;

        [ProtoBuf.ProtoMember(2)]
        public int index;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_PROGRESS_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint mapId;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] progressRewards;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_EVENT
    {
        [ProtoBuf.ProtoMember(1)]
        public int index;

        [ProtoBuf.ProtoMember(2)]
        public uint option;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_EVENT
    {
        [ProtoBuf.ProtoMember(1)]
        public int index;

        [ProtoBuf.ProtoMember(2)]
        public uint option;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> reward = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> waitSettleRewards = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ADVENTURE_SETTLE_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ADVENTURE_SETTLE_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ADVENTURE_TOUR_VO adventureTour;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
