// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: arena.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.arena
{
    [ProtoBuf.ProtoContract]
    public class I_RANK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint score;

        [ProtoBuf.ProtoMember(2)]
        public uint targetId;

        [ProtoBuf.ProtoMember(3)]
        public uint role;

        [ProtoBuf.ProtoMember(4)]
        public uint rank;

    }

    [ProtoBuf.ProtoContract]
    public class I_RIVAL_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public uint role;

        [ProtoBuf.ProtoMember(3)]
        public uint score;

    }

    [ProtoBuf.ProtoContract]
    public class I_BATTLE_LOG_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.fight.I_BATTLE_RESULT battleResult;

        [ProtoBuf.ProtoMember(2)]
        public int score;

        [ProtoBuf.ProtoMember(3)]
        public uint logTime;

        [ProtoBuf.ProtoMember(4)]
        public I_RIVAL_VO rivalUserInfo;

        [ProtoBuf.ProtoMember(5)]
        public uint logId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_RANK_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_RANK_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_RANK_VO> rankList = new System.Collections.Generic.List<I_RANK_VO>();

        [ProtoBuf.ProtoMember(3)]
        public I_MY_RANK myRank;

        [ProtoBuf.ProtoContract]
        public class I_MY_RANK
        {
            [ProtoBuf.ProtoMember(1)]
            public uint rank;

            [ProtoBuf.ProtoMember(2)]
            public uint score;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_RIVAL
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_RIVAL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_RIVAL_VO> rivalUserInfos = new System.Collections.Generic.List<I_RIVAL_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_REFRESH_RIVAL
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_REFRESH_RIVAL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint arenaRefreshCnt;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_RIVAL_VO> rivalUserInfos = new System.Collections.Generic.List<I_RIVAL_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_FIGHT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint rivalIndex;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_FIGHT
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.fight.I_BATTLE_RESULT battleResult;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_RIVAL_VO> rivalUserInfos = new System.Collections.Generic.List<I_RIVAL_VO>();

        [ProtoBuf.ProtoMember(3)]
        public int score;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_FIGHTLOG
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_FIGHTLOG
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_BATTLE_LOG_VO> battleLog = new System.Collections.Generic.List<I_BATTLE_LOG_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ARENA_REVENGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint logId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ARENA_REVENGE
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.fight.I_BATTLE_RESULT battleResult;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_RIVAL_VO> rivalUserInfos = new System.Collections.Generic.List<I_RIVAL_VO>();

        [ProtoBuf.ProtoMember(3)]
        public int score;

        [ProtoBuf.ProtoMember(4)]
        public uint logId;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
