// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: card.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.card
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_DRAW_CARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRAW_CARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.item.I_ITEM_VO> itemList = new System.Collections.Generic.List<protobuf.item.I_ITEM_VO>();

        [ProtoBuf.ProtoMember(3)]
        public uint luckyValue;

        [ProtoBuf.ProtoMember(4)]
        public uint activityId;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRAW_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRAW_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public DRAW_INFO drawInfo;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT> exchangeStat = new System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT>();

        [ProtoBuf.ProtoContract]
        public class DRAW_INFO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint activityId;

            [ProtoBuf.ProtoMember(2)]
            public uint luckyValue;

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021
