// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: chat.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.guild
{
    [ProtoBuf.ProtoContract]
    public class I_SEND_CHAT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint contentType;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string content = "";

        [ProtoBuf.ProtoMember(3)]
        public REFERER_CHAT_VO referer;

        [ProtoBuf.ProtoContract]
        public class REFERER_CHAT_VO
        {
            [ProtoBuf.ProtoMember(1)]
            [System.ComponentModel.DefaultValue("")]
            public string nickName = "";

            [ProtoBuf.ProtoMember(2)]
            public uint contentType;

            [ProtoBuf.ProtoMember(3)]
            [System.ComponentModel.DefaultValue("")]
            public string content = "";

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_WORLD_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SEND_CHAT_VO chatContent;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_WORLD_CHAT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_WORLD_RECEIVE_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public I_SEND_CHAT_VO chatContent;

        [ProtoBuf.ProtoMember(3)]
        public uint operateTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SEND_CHAT_VO chatContent;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_CHAT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_RECEIVE_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public I_SEND_CHAT_VO chatContent;

        [ProtoBuf.ProtoMember(3)]
        public uint operateTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_WORLD_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_WORLD_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<S_MSG_GUILD_RECEIVE_CHAT> chatHistory = new System.Collections.Generic.List<S_MSG_GUILD_RECEIVE_CHAT>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<S_MSG_GUILD_RECEIVE_CHAT> chatHistory = new System.Collections.Generic.List<S_MSG_GUILD_RECEIVE_CHAT>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CREATE_FRIEND_CONTACT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CREATE_FRIEND_CONTACT
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE contractUserInfo;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DEL_FRIEND_CONTACT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DEL_FRIEND_CONTACT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_CONTACT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_CONTACT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> contractUserInfos = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SEND_CHAT_VO chatContent;

        [ProtoBuf.ProtoMember(2)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SEND_CHAT_VO chatContent;

        [ProtoBuf.ProtoMember(2)]
        public uint operateTime;

        [ProtoBuf.ProtoMember(3)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_RECEIVE_CHAT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SEND_CHAT_VO chatContent;

        [ProtoBuf.ProtoMember(2)]
        public uint operateTime;

        [ProtoBuf.ProtoMember(3)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_CHAT_HISTORY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FRIEND_CHAT_HISTORY> chatHistory = new System.Collections.Generic.List<I_FRIEND_CHAT_HISTORY>();

        [ProtoBuf.ProtoMember(2)]
        public uint friendId;

        [ProtoBuf.ProtoContract]
        public class I_FRIEND_CHAT_HISTORY
        {
            [ProtoBuf.ProtoMember(1)]
            public I_SEND_CHAT_VO chatContent;

            [ProtoBuf.ProtoMember(2)]
            public uint operateTime;

            [ProtoBuf.ProtoMember(3)]
            public bool isSelf;

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021
