// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: commonActivity.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.commonActivity
{
    [ProtoBuf.ProtoContract]
    public class I_EXCHANGE_STAT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint exchangeId;

        [ProtoBuf.ProtoMember(2)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_COMMONACTIVITY_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint exchangeId;

        [ProtoBuf.ProtoMember(3)]
        public uint module;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_COMMONACTIVITY_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint exchangeId;

        [ProtoBuf.ProtoMember(3)]
        public I_EXCHANGE_STAT exchange;

        [ProtoBuf.ProtoMember(4)]
        public uint module;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
