// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: common.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.common
{
    [ProtoBuf.ProtoContract]
    public class S_Exception
    {
        [ProtoBuf.ProtoMember(1)]
        public uint code;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string message = "";

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string trace = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_READY
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_EMPTY
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_GM_SEND_ITEM
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public long count;

    }

    [ProtoBuf.ProtoContract]
    public class S_GM_SEND_ITEM
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public long count;

    }

    [ProtoBuf.ProtoContract]
    public class C_GM_UPDATE_TOWNNAME
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_GM_UPDATE_TOWNNAME
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAINTASK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint mainTaskId;

        [ProtoBuf.ProtoMember(2)]
        public uint mainTaskCnt;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAINTASK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint mainTaskId;

        [ProtoBuf.ProtoMember(2)]
        public uint mainTaskCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_GM_UPDATE_TIMEOFFSET
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string offsetTime = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_GM_UPDATE_TIMEOFFSET
    {
        [ProtoBuf.ProtoMember(1)]
        public uint serverTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_USER_PROFILE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint userLevel;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string headImgId = "";

        [ProtoBuf.ProtoMember(5)]
        public uint headFrame;

        [ProtoBuf.ProtoMember(8)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(9)]
        public uint fighting;

        [ProtoBuf.ProtoMember(10)]
        public uint dressCharm;

        [ProtoBuf.ProtoMember(11)]
        public uint title;

        [ProtoBuf.ProtoMember(12)]
        public uint serverId;

    }

    [ProtoBuf.ProtoContract]
    public class C_PING
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_PING
    {
        [ProtoBuf.ProtoMember(1)]
        public uint clientTime;

        [ProtoBuf.ProtoMember(2)]
        public uint serverTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_NOTICE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint noticeId;

        [ProtoBuf.ProtoMember(2)]
        public uint startTime;

        [ProtoBuf.ProtoMember(3)]
        public uint endTime;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string title = "";

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string content = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021
