// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: contract.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.card
{
    [ProtoBuf.ProtoContract]
    public class I_CONTRACT_TASK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint taskId;

        [ProtoBuf.ProtoMember(3)]
        public uint needCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint curCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint awardStatus;

    }

    [ProtoBuf.ProtoContract]
    public class I_CONTRACT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint exp;

        [ProtoBuf.ProtoMember(2)]
        public uint seniorType;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] normalRewardLevels;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] seniorRewardLvels;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CONTRACT_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CONTRACT_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_CONTRACT_VO contract;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_CONTRACT_TASK_VO> contractTaskList = new System.Collections.Generic.List<I_CONTRACT_TASK_VO>();

        [ProtoBuf.ProtoMember(3)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CONTRACT_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CONTRACT_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

        [ProtoBuf.ProtoMember(3)]
        public uint exp;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CONTRACT_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint isSenior;

        [ProtoBuf.ProtoMember(3)]
        public uint level;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CONTRACT_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint isSenior;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] normalRewardLevels;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] seniorRewardLevels;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<long, long> items = new System.Collections.Generic.Dictionary<long, long>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
