// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: crony.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.friend
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_CRONY_VO> cronyList = new System.Collections.Generic.List<I_CRONY_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint unlockCronyCnt;

        [ProtoBuf.ProtoContract]
        public class I_CRONY_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint friendId;

            [ProtoBuf.ProtoMember(2)]
            public uint exp;

            [ProtoBuf.ProtoMember(3)]
            public uint cancelTime;

            [ProtoBuf.ProtoMember(4)]
            public uint isInitiative;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_BE_APPLY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_BE_APPLY
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] applyUserIds;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_AGREE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_AGREE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint status;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_REJECT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_REJECT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_BUY_BOOKITEM
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_BUY_BOOKITEM
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint cancelTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_BACKOUT_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_BACKOUT_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_SPEED_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_SPEED_CANCEL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_UNLOCK_CNT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_UNLOCK_CNT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint unlockCronyCnt;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
