// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: crystaln.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.login
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_CRYSTALN_COLLECT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRYSTALN_COLLECT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
