// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: cultivateresearch.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.cultivateresearch
{
    [ProtoBuf.ProtoContract]
    public class I_CULTIVATION_RESEARCH_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint luckNum;

        [ProtoBuf.ProtoMember(2)]
        public uint needItemId;

        [ProtoBuf.ProtoMember(3)]
        public uint changeTime;

        [ProtoBuf.ProtoMember(4)]
        public uint coolingTime;

        [ProtoBuf.ProtoMember(5)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(6)]
        public uint flowerNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_CULTIVATION_RESEARCH_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_CULTIVATION_RESEARCH_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_CULTIVATION_RESEARCH_VO cultivateSearch;

    }

    [ProtoBuf.ProtoContract]
    public class C_CULTIVATION_RESEARCH_START
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemNum;

    }

    [ProtoBuf.ProtoContract]
    public class S_CULTIVATION_RESEARCH_START
    {
        [ProtoBuf.ProtoMember(1)]
        public uint luckNum;

        [ProtoBuf.ProtoMember(2)]
        public uint coolingTime;

        [ProtoBuf.ProtoMember(3)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(4)]
        public uint flowerNum;

        [ProtoBuf.ProtoMember(5)]
        public uint needItemId;

        [ProtoBuf.ProtoMember(6)]
        public uint itemNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_CULTIVATION_RESEARCH_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_CULTIVATION_RESEARCH_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint needItemId;

        [ProtoBuf.ProtoMember(2)]
        public uint changeTime;

        [ProtoBuf.ProtoMember(3)]
        public uint coolingTime;

        [ProtoBuf.ProtoMember(4)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(5)]
        public uint flowerNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_CULTIVATION_RESEARCH_COOLTIME_CLEAR
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_CULTIVATION_RESEARCH_COOLTIME_CLEAR
    {
        [ProtoBuf.ProtoMember(1)]
        public uint coolingTime;

        [ProtoBuf.ProtoMember(2)]
        public uint changeTime;

        [ProtoBuf.ProtoMember(3)]
        public uint needItemId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
