// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: cultivateshop.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.cultivateshop
{
    [ProtoBuf.ProtoContract]
    public class I_SHOP_ITEM
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint itemCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint price;

        [ProtoBuf.ProtoMember(5)]
        public uint isBuy;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_SHOP
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_SHOP
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_SHOP_ITEM> cultivateShops = new System.Collections.Generic.List<I_SHOP_ITEM>();

        [ProtoBuf.ProtoMember(2)]
        public uint refreshTime;

        [ProtoBuf.ProtoMember(3)]
        public uint refreshCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_REFRESH
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_REFRESH
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_SHOP_ITEM> cultivateShops = new System.Collections.Generic.List<I_SHOP_ITEM>();

        [ProtoBuf.ProtoMember(2)]
        public uint refreshTime;

        [ProtoBuf.ProtoMember(3)]
        public uint refreshCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public I_SHOP_ITEM cultivateShop;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
