// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: dailyTask.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.dailyTask
{
    [ProtoBuf.ProtoContract]
    public class I_TASK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint taskId;

        [ProtoBuf.ProtoMember(3)]
        public uint curCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint needNum;

        [ProtoBuf.ProtoMember(5)]
        public uint awardStatus;

        [ProtoBuf.ProtoMember(6)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class I_ACHIEV_TASK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint taskId;

        [ProtoBuf.ProtoMember(2)]
        public uint seriesId;

        [ProtoBuf.ProtoMember(3)]
        public uint curCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_TASK
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_TASK
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_TASK_VO> dailyTask = new System.Collections.Generic.List<I_TASK_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_TASK_VO> weeklyTask = new System.Collections.Generic.List<I_TASK_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_TASK_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_TASK_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_TASK_VO dailyTask;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TASK_PROGRESS_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TASK_PROGRESS_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

        [ProtoBuf.ProtoMember(3)]
        public uint type;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] rewardIds;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAINTASK_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAINTASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint mainTaskCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint mainTaskId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ACHIEV_TASK_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ACHIEV_TASK_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ACHIEV_TASK_VO> achievTaskList = new System.Collections.Generic.List<I_ACHIEV_TASK_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ACHIEV_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint seriesId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ACHIEV_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint seriesId;

        [ProtoBuf.ProtoMember(3)]
        public I_ACHIEV_TASK_VO achievTask;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROOKIE_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROOKIE_REWARD
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] rookieRewards;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROOKIE_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROOKIE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ROOKIE_TASK> rookieTask = new System.Collections.Generic.List<I_ROOKIE_TASK>();

        [ProtoBuf.ProtoMember(2)]
        public uint days;

        [ProtoBuf.ProtoContract]
        public class I_ROOKIE_TASK
        {
            [ProtoBuf.ProtoMember(1)]
            public uint indexId;

            [ProtoBuf.ProtoMember(2)]
            public uint curCnt;

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021
