// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: dress.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.dress
{
    [ProtoBuf.ProtoContract]
    public class I_DRESS_INFO
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] ware;

    }

    [ProtoBuf.ProtoContract]
    public class I_SUIT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint suitId;

        [ProtoBuf.ProtoMember(2)]
        public uint starLv;

        [ProtoBuf.ProtoMember(3)]
        public uint gradeLv;

    }

    [ProtoBuf.ProtoContract]
    public class I_DRESS_SUIT_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_SUIT_VO> suitList = new System.Collections.Generic.List<I_SUIT_VO>();

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] ware;

        [ProtoBuf.ProtoMember(3)]
        public uint score;

        [ProtoBuf.ProtoMember(4)]
        public uint rewardId;

        [ProtoBuf.ProtoMember(5)]
        public uint dressDrawingPower;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_SUIT_VO> suitList = new System.Collections.Generic.List<I_SUIT_VO>();

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] ware;

        [ProtoBuf.ProtoMember(3)]
        public uint score;

        [ProtoBuf.ProtoMember(4)]
        public uint rewardId;

        [ProtoBuf.ProtoMember(5)]
        public uint dressShopExp;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_WARE
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string clothesIds = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_WARE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] ware;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint score;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<protobuf.item.I_ITEM_VO> itemList = new System.Collections.Generic.List<protobuf.item.I_ITEM_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_SCORE_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_SCORE_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint score;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint rewardId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_STAR_LV
    {
        [ProtoBuf.ProtoMember(1)]
        public uint suitId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_STAR_LV
    {
        [ProtoBuf.ProtoMember(1)]
        public uint suitId;

        [ProtoBuf.ProtoMember(2)]
        public uint starLv;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_UPGRADE_LV
    {
        [ProtoBuf.ProtoMember(1)]
        public uint suitId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_UPGRADE_LV
    {
        [ProtoBuf.ProtoMember(1)]
        public uint suitId;

        [ProtoBuf.ProtoMember(2)]
        public uint gradeLv;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DRESS_CLOTHES_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DRESS_CLOTHES_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint dressShopExp;

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
