// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: fairy.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.fairy
{
    [ProtoBuf.ProtoContract]
    public class I_FAIRY_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fairyId;

        [ProtoBuf.ProtoMember(2)]
        public int level;

    }

    [ProtoBuf.ProtoContract]
    public class I_ALTAR_VO
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public ulong[] fairyShardIds;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] drawIndex;

        [ProtoBuf.ProtoMember(3)]
        public uint lucky;

        [ProtoBuf.ProtoMember(4)]
        public uint luckyId;

        [ProtoBuf.ProtoMember(5)]
        public uint refreshTime;

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.Dictionary<uint, uint> relationsLevel = new System.Collections.Generic.Dictionary<uint, uint>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ALTAR_VO altar;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint multi;

        [ProtoBuf.ProtoMember(2)]
        public uint refreshTime;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ALTAR_VO altar;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fairyId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FAIRY_VO fairy;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fairyId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FAIRY_VO fairy;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_REFRESH
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_REFRESH
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ALTAR_VO altar;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_UPGRADE_RELATION
    {
        [ProtoBuf.ProtoMember(1)]
        public uint relationId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_UPGRADE_RELATION
    {
        [ProtoBuf.ProtoMember(1)]
        public uint relationId;

        [ProtoBuf.ProtoMember(2)]
        public uint relationsLevel;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
