// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: fairyflower.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.card
{
    [ProtoBuf.ProtoContract]
    public class I_FAIRY_CONTRACT_TASK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint taskId;

        [ProtoBuf.ProtoMember(3)]
        public uint needCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint curCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint awardStatus;

    }

    [ProtoBuf.ProtoContract]
    public class I_FAIRY_CONTRACT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint exp;

        [ProtoBuf.ProtoMember(2)]
        public uint seniorType;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] normalRewardLevels;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] seniorRewardLvels;

        [ProtoBuf.ProtoMember(5)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class I_HELP
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] helpFriendIds;

        [ProtoBuf.ProtoMember(2)]
        public uint status;

        [ProtoBuf.ProtoMember(3)]
        public uint effectTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_DISPATCH_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint fairyId;

        [ProtoBuf.ProtoMember(3)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(4)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_FAIRY_FIGURE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint figureId;

        [ProtoBuf.ProtoMember(2)]
        public uint level;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLOWER_FAIRY_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FAIRY_FIGURE_VO figuire;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLOWER_FAIRY_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_HELP help;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_DISPATCH_VO> fairyDispatchList = new System.Collections.Generic.List<I_DISPATCH_VO>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_FAIRY_FIGURE_VO> figureList = new System.Collections.Generic.List<I_FAIRY_FIGURE_VO>();

        [ProtoBuf.ProtoMember(4)]
        public I_FAIRY_CONTRACT_VO fairContract;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<I_FAIRY_CONTRACT_TASK_VO> fairContractTaskList = new System.Collections.Generic.List<I_FAIRY_CONTRACT_TASK_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_CONTRACT_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_CONTRACT_TASK_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

        [ProtoBuf.ProtoMember(3)]
        public uint exp;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_CONTRACT_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint isSenior;

        [ProtoBuf.ProtoMember(3)]
        public uint level;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_CONTRACT_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint isSenior;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] normalRewardLevels;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] seniorRewardLevels;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<long, long> items = new System.Collections.Generic.Dictionary<long, long>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_FIGUIRE_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint figureId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_FIGUIRE_UPGRADE
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_BLIND_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_BLIND_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_DISPATCH
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint fairyId;

        [ProtoBuf.ProtoMember(3)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_DISPATCH
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public I_DISPATCH_VO fairyDispatch;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_DISPATCH_UNLOCK_POS
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_DISPATCH_UNLOCK_POS
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public I_DISPATCH_VO fairyDispatch;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_DISPATCH_SPEED
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_DISPATCH_SPEED
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public I_DISPATCH_VO fairyDispatch;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_DISPATCH_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_DISPATCH_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public I_DISPATCH_VO fairyDispatch;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_HELP_APPLY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_HELP_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint status;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_HELP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_HELP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint helpStatus;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_HELP_EFFECT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_HELP_EFFECT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint status;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FAIRY_BLIND_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FAIRY_BLIND_INFO
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] openPos;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
