// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: fight.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.fight
{
    [ProtoBuf.ProtoContract]
    public class I_BUFF_SEQ_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint t;

        [ProtoBuf.ProtoMember(2)]
        public uint s;

        [ProtoBuf.ProtoMember(3)]
        public int sid;

        [ProtoBuf.ProtoMember(4)]
        public ulong buffId;

        [ProtoBuf.ProtoMember(5)]
        public bool f;

        [ProtoBuf.ProtoMember(6)]
        public uint v;

        [ProtoBuf.ProtoMember(7)]
        public ulong skillId;

        [ProtoBuf.ProtoMember(8)]
        public bool isChangeHealth;

    }

    [ProtoBuf.ProtoContract]
    public class I_BATTLE_ROUND_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong round;

        [ProtoBuf.ProtoMember(2)]
        public bool isCrit;

        [ProtoBuf.ProtoMember(3)]
        public bool isAttacker;

        [ProtoBuf.ProtoMember(4)]
        public bool isDodge;

        [ProtoBuf.ProtoMember(5)]
        public bool isStun;

        [ProtoBuf.ProtoMember(6)]
        public bool isChase;

        [ProtoBuf.ProtoMember(7)]
        public ulong reflect;

        [ProtoBuf.ProtoMember(8)]
        public ulong lifesteal;

        [ProtoBuf.ProtoMember(9)]
        public ulong myHealth;

        [ProtoBuf.ProtoMember(10)]
        public ulong enemyHealth;

        [ProtoBuf.ProtoMember(11)]
        public System.Collections.Generic.List<I_BUFF_SEQ_VO> buffSeq = new System.Collections.Generic.List<I_BUFF_SEQ_VO>();

        [ProtoBuf.ProtoMember(12)]
        public uint enemyId;

        [ProtoBuf.ProtoMember(13)]
        public uint userId;

    }

    [ProtoBuf.ProtoContract]
    public class I_BATTLE_PLAYER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong health;

        [ProtoBuf.ProtoMember(2)]
        public ulong maxHealth;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public ulong[] battlePetIds;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public ulong[] battleFairyIds;

    }

    [ProtoBuf.ProtoContract]
    public class I_FIGHT_ATTRIBUTES_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint attack;

        [ProtoBuf.ProtoMember(2)]
        public uint defense;

        [ProtoBuf.ProtoMember(3)]
        public uint health;

        [ProtoBuf.ProtoMember(4)]
        public uint speed;

        [ProtoBuf.ProtoMember(5)]
        public float critRate;

        [ProtoBuf.ProtoMember(6)]
        public float critResistanceRate;

        [ProtoBuf.ProtoMember(7)]
        public float dodgeRate;

        [ProtoBuf.ProtoMember(8)]
        public float dodgeResistanceRate;

        [ProtoBuf.ProtoMember(9)]
        public float stunRate;

        [ProtoBuf.ProtoMember(10)]
        public float stuneResistanceRate;

        [ProtoBuf.ProtoMember(11)]
        public float chaseRate;

        [ProtoBuf.ProtoMember(12)]
        public float lifestealPer;

        [ProtoBuf.ProtoMember(13)]
        public float lifestealResistancePer;

        [ProtoBuf.ProtoMember(14)]
        public float reflectPer;

        [ProtoBuf.ProtoMember(15)]
        public float reflectResistancePer;

        [ProtoBuf.ProtoMember(16)]
        public float innoreRate;

        [ProtoBuf.ProtoMember(17)]
        public float innoreResistanceRate;

        [ProtoBuf.ProtoMember(18)]
        public float finalIncreaseDamagePer;

        [ProtoBuf.ProtoMember(19)]
        public float finalDefensePer;

        [ProtoBuf.ProtoMember(20)]
        public float finalPetIncreasePer;

        [ProtoBuf.ProtoMember(21)]
        public float finalPetDecreasePer;

        [ProtoBuf.ProtoMember(22)]
        public float finalHealPer;

        [ProtoBuf.ProtoMember(23)]
        public float finalHealResistancePer;

    }

    [ProtoBuf.ProtoContract]
    public class I_BATTLE_RESULT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_BATTLE_PLAYER_VO me;

        [ProtoBuf.ProtoMember(2)]
        public I_BATTLE_PLAYER_VO enemy;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_BATTLE_ROUND_VO> roundDetails = new System.Collections.Generic.List<I_BATTLE_ROUND_VO>();

        [ProtoBuf.ProtoMember(4)]
        public bool isWin;

        [ProtoBuf.ProtoMember(5)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_BATTLE_PET
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint petId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_BATTLE_PET
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] battlePets;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_BATTLE_FAIRY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint fairyId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_BATTLE_FAIRY
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] battleFairys;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
