// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: floristshop.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.floristshop
{
    [ProtoBuf.ProtoContract]
    public class I_FURNITURE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public uint floor;

        [ProtoBuf.ProtoMember(3)]
        public uint x;

        [ProtoBuf.ProtoMember(4)]
        public uint y;

    }

    [ProtoBuf.ProtoContract]
    public class I_FLORIST_SHOP_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint level;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] rewardIds;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_FURNITURE_VO> decoration = new System.Collections.Generic.List<I_FURNITURE_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLORIST_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLORIST_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FLORIST_SHOP_VO floristShop;

        [ProtoBuf.ProtoMember(2)]
        public ulong floristDrawingPower;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLORIST_CONDITIION_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLORIST_CONDITIION_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLORIST_UPGRADE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLORIST_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FLORIST_SHOP_VO floristShop;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLORIST_DECORATION
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FURNITURE_VO> decoration = new System.Collections.Generic.List<I_FURNITURE_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLORIST_DECORATION
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLORIST_FURNITURE_FORGE
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong furnitureId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLORIST_FURNITURE_FORGE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
