// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: flowerorder.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.npcorder
{
    [ProtoBuf.ProtoContract]
    public class I_FLOWERORDER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> needItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint expBuff;

        [ProtoBuf.ProtoMember(3)]
        public uint goldBuff;

        [ProtoBuf.ProtoMember(4)]
        public uint refreshTimes;

        [ProtoBuf.ProtoMember(5)]
        public uint status;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLOWERORDER_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLOWERORDER_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FLOWERORDER_VO flowerOrder;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLOWERORDER_SUBMIT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLOWERORDER_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FLOWERORDER_REFRESH
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FLOWERORDER_REFRESH
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FLOWERORDER_VO flowerOrder;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
