// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: flowerstar.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.flowerstar
{
    [ProtoBuf.ProtoContract]
    public class I_FLOWERSTAR_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<uint, uint> buff = new System.Collections.Generic.Dictionary<uint, uint>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<uint, uint> upgradeBuff = new System.Collections.Generic.Dictionary<uint, uint>();

    }

    [ProtoBuf.ProtoContract]
    public class C_FLOWERSTAR_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_FLOWERSTAR_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

        [ProtoBuf.ProtoMember(3)]
        public uint buffId;

    }

    [ProtoBuf.ProtoContract]
    public class C_FLOWERSTAR_UPGREADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_FLOWERSTAR_UPGREADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

        [ProtoBuf.ProtoMember(3)]
        public uint buffId;

    }

    [ProtoBuf.ProtoContract]
    public class C_FLOWERSTAR_REPLACE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_FLOWERSTAR_REPLACE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public int pos;

        [ProtoBuf.ProtoMember(3)]
        public uint buffId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
