// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: friend.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.friend
{
    [ProtoBuf.ProtoContract]
    public class I_FRIEND_PROFILE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint userLevel;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string headImgId = "";

        [ProtoBuf.ProtoMember(5)]
        public uint headFrame;

        [ProtoBuf.ProtoMember(8)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(9)]
        public bool isMark;

        [ProtoBuf.ProtoMember(10)]
        public bool canSteal;

        [ProtoBuf.ProtoMember(11)]
        public ulong fighting;

        [ProtoBuf.ProtoMember(12)]
        public uint title;

        [ProtoBuf.ProtoMember(13)]
        public uint serverId;

    }

    [ProtoBuf.ProtoContract]
    public class I_CRONY_FRIEND_PROFILE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint userLevel;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string headImgId = "";

        [ProtoBuf.ProtoMember(5)]
        public uint headFrame;

        [ProtoBuf.ProtoMember(6)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(7)]
        public uint title;

        [ProtoBuf.ProtoMember(8)]
        public uint serverId;

        [ProtoBuf.ProtoMember(9)]
        public ulong fighting;

        [ProtoBuf.ProtoMember(10)]
        public ulong time;

        [ProtoBuf.ProtoMember(11)]
        public bool isCrony;

        [ProtoBuf.ProtoMember(12)]
        public bool isApplyCrony;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint start;

        [ProtoBuf.ProtoMember(2)]
        public uint end;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FRIEND_PROFILE> friendList = new System.Collections.Generic.List<I_FRIEND_PROFILE>();

        [ProtoBuf.ProtoMember(2)]
        public uint count;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_VISIT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_VISIT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.plant.I_PLANT_STEAL_VO> plantList = new System.Collections.Generic.List<protobuf.plant.I_PLANT_STEAL_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.table.I_TABLE_VO> tableList = new System.Collections.Generic.List<protobuf.table.I_TABLE_VO>();

        [ProtoBuf.ProtoMember(3)]
        public protobuf.user.I_PROFILE_VO profile;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<protobuf.user.I_PROFILE_INFO_VO> profileInfos = new System.Collections.Generic.List<protobuf.user.I_PROFILE_INFO_VO>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO> npcOrderOldList = new System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO>();

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO> npcOrderNewList = new System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO>();

        [ProtoBuf.ProtoMember(7)]
        public uint npcOrderRefreshTime;

        [ProtoBuf.ProtoMember(8)]
        public System.Collections.Generic.List<protobuf.order.I_ORDER_VO> orderList = new System.Collections.Generic.List<protobuf.order.I_ORDER_VO>();

        [ProtoBuf.ProtoMember(9)]
        public uint serverTime;

        [ProtoBuf.ProtoMember(10)]
        public uint friendId;

        [ProtoBuf.ProtoMember(11)]
        public uint interactionCnt;

        [ProtoBuf.ProtoMember(12)]
        public protobuf.dress.I_DRESS_INFO dress;

        [ProtoBuf.ProtoMember(13)]
        public protobuf.floristshop.I_FLORIST_SHOP_VO floristShop;

        [ProtoBuf.ProtoMember(14)]
        public uint friendCoinExchangeCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_STEAL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint decorId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_STEAL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint decorId;

        [ProtoBuf.ProtoMember(2)]
        public uint interactionCnt;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<long, long> items = new System.Collections.Generic.Dictionary<long, long>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_BATCH_STEAL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_BATCH_STEAL
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

        [ProtoBuf.ProtoMember(2)]
        public uint interactionCnt;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<long, long> items = new System.Collections.Generic.Dictionary<long, long>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_APPLY
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] friendIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_APPLY
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] effectFriendIds;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_APPLY_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_APPLY_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> applyList = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_REJECT
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] friendIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_REJECT
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] friendIds;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_AGREE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] friendIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_AGREE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] effectFriendIds;

        [ProtoBuf.ProtoMember(2)]
        public uint friendCount;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_MARK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public bool mark;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_MARK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public bool mark;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint friendCount;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_INSERT_BLACK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_INSERT_BLACK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint friendCount;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_BLACK_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_BLACK_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> blackList = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_BLACK_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_BLACK_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_RECOMMEND_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_RECOMMEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> recommendList = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIENDCOIN_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendId;

        [ProtoBuf.ProtoMember(2)]
        public uint count;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIENDCOIN_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint friendCoinExchangeCnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_STEAL_MESSAGE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ITEM_VO> items = new System.Collections.Generic.List<I_ITEM_VO>();

        [ProtoBuf.ProtoMember(2)]
        public I_FRIEND_PROFILE userInfo;

        [ProtoBuf.ProtoMember(3)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(4)]
        public uint reqTime;

        [ProtoBuf.ProtoContract]
        public class I_ITEM_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public ulong itemId;

            [ProtoBuf.ProtoMember(2)]
            public uint cnt;

            [ProtoBuf.ProtoMember(3)]
            public uint cronyCnt;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FRIEND_STEAL_MESSAGE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FRIEND_STEAL_MESSAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fcoinDailyCnt;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_STEAL_MESSAGE_VO> messageList = new System.Collections.Generic.List<I_STEAL_MESSAGE_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CRONY_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint start;

        [ProtoBuf.ProtoMember(2)]
        public uint end;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CRONY_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_CRONY_FRIEND_PROFILE> friendList = new System.Collections.Generic.List<I_CRONY_FRIEND_PROFILE>();

        [ProtoBuf.ProtoMember(2)]
        public uint count;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
