// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: fund.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.fund
{
    [ProtoBuf.ProtoContract]
    public class I_FUND_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fundType;

        [ProtoBuf.ProtoMember(2)]
        public int triggerTime;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] stageReward;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FUND_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fundType;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FUND_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint fundType;

        [ProtoBuf.ProtoMember(2)]
        public I_FUND_VO fundVo;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
