// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: goal.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.goal
{
    [ProtoBuf.ProtoContract]
    public class I_ACTIVITY_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint totalItemNum;

        [ProtoBuf.ProtoMember(2)]
        public uint buyTime;

        [ProtoBuf.ProtoMember(3)]
        public uint consumeItemNum;

        [ProtoBuf.ProtoMember(4)]
        public uint itemCnt;

        [ProtoBuf.ProtoMember(5, IsPacked = true)]
        public uint[] goalRewardIds;

    }

    [ProtoBuf.ProtoContract]
    public class I_SUNSHINE_ORDER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(3)]
        public uint submitTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint itemCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_REWARD
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] goalRewardIds;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint itemCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint totalItemNum;

        [ProtoBuf.ProtoMember(5)]
        public uint buyTime;

        [ProtoBuf.ProtoMember(6)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_REFRESH_COOLTIME
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_REFRESH_COOLTIME
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint buyTime;

        [ProtoBuf.ProtoMember(3)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ACTIVITY_INFO info;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SUNSHINE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SUNSHINE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ACTIVITY_INFO info;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_SUNSHINE_ORDER_VO> orderList = new System.Collections.Generic.List<I_SUNSHINE_ORDER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_SUBMIT_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

        [ProtoBuf.ProtoMember(3)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_SUBMIT_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint submitTime;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GOAL_REFRESH_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint activityId;

        [ProtoBuf.ProtoMember(2)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GOAL_REFRESH_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public I_SUNSHINE_ORDER_VO order;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
