// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: guild.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.guild
{
    [ProtoBuf.ProtoContract]
    public class I_GUILD_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint guildId;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string guildName = "";

        [ProtoBuf.ProtoMember(3)]
        public uint level;

        [ProtoBuf.ProtoMember(4)]
        public uint presidentId;

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string flagId = "";

        [ProtoBuf.ProtoMember(6)]
        [System.ComponentModel.DefaultValue("")]
        public string notice = "";

        [ProtoBuf.ProtoMember(8)]
        public uint reviewType;

        [ProtoBuf.ProtoMember(9)]
        public uint memberLimitLevel;

        [ProtoBuf.ProtoMember(10)]
        public uint memberLimitFighting;

        [ProtoBuf.ProtoMember(11)]
        public ulong fighting;

        [ProtoBuf.ProtoMember(12)]
        public uint memberCnt;

        [ProtoBuf.ProtoMember(13)]
        public uint gold;

        [ProtoBuf.ProtoMember(14)]
        public uint giftScore;

        [ProtoBuf.ProtoMember(15)]
        public uint competitionWeight;

    }

    [ProtoBuf.ProtoContract]
    public class I_GUILD_LIST_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint guildId;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string guildName = "";

        [ProtoBuf.ProtoMember(3)]
        public uint level;

        [ProtoBuf.ProtoMember(4)]
        public uint presidentId;

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string flagId = "";

        [ProtoBuf.ProtoMember(6)]
        [System.ComponentModel.DefaultValue("")]
        public string notice = "";

        [ProtoBuf.ProtoMember(8)]
        public uint reviewType;

        [ProtoBuf.ProtoMember(9)]
        public uint memberLimitLevel;

        [ProtoBuf.ProtoMember(10)]
        public uint memberLimitFighting;

        [ProtoBuf.ProtoMember(11)]
        public ulong fighting;

        [ProtoBuf.ProtoMember(12)]
        public uint memberCnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_FLOWERPOT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint level;

        [ProtoBuf.ProtoMember(3)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(4)]
        public uint plantTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_POSITION_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string positionName = "";

    }

    [ProtoBuf.ProtoContract]
    public class I_PRESIDENT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint userLevel;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string headImgId = "";

        [ProtoBuf.ProtoMember(5)]
        public uint headFrame;

        [ProtoBuf.ProtoMember(6)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(7)]
        public uint fighting;

        [ProtoBuf.ProtoMember(8)]
        public uint title;

        [ProtoBuf.ProtoMember(9)]
        public uint serverId;

    }

    [ProtoBuf.ProtoContract]
    public class I_MEMBER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint userLevel;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string headImgId = "";

        [ProtoBuf.ProtoMember(5)]
        public uint headFrame;

        [ProtoBuf.ProtoMember(8)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(9)]
        public uint powerId;

        [ProtoBuf.ProtoMember(10)]
        public uint fighting;

        [ProtoBuf.ProtoMember(11)]
        public bool online;

        [ProtoBuf.ProtoMember(12)]
        public uint money;

        [ProtoBuf.ProtoMember(13)]
        public uint donateCnt;

        [ProtoBuf.ProtoMember(14)]
        public uint title;

        [ProtoBuf.ProtoMember(15)]
        public uint serverId;

    }

    [ProtoBuf.ProtoContract]
    public class I_BRIEF_MEMBER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint powerId;

        [ProtoBuf.ProtoMember(3)]
        public uint money;

        [ProtoBuf.ProtoMember(4)]
        public uint donateCnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_APPLY_MEMBER_VO
    {
    }

    [ProtoBuf.ProtoContract]
    public class I_GUILD_ME_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint powerId;

        [ProtoBuf.ProtoMember(2)]
        public uint donateCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_FOUND
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string guildName = "";

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string flagId = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_FOUND
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GUILD_VO guild;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_MEMBERLIST
    {
        [ProtoBuf.ProtoMember(1)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_MEMBERLIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MEMBER_VO> memberList = new System.Collections.Generic.List<I_MEMBER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_BATCH_MEMBER_INFO
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] userIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_BATCH_MEMBER_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MEMBER_VO> memberList = new System.Collections.Generic.List<I_MEMBER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GUILD_VO guild;

        [ProtoBuf.ProtoMember(2)]
        public I_PRESIDENT_VO presidentInfo;

        [ProtoBuf.ProtoMember(3)]
        public I_GUILD_ME_VO me;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] haveDrawDonateIds;

        [ProtoBuf.ProtoMember(5)]
        public uint guildDonate;

        [ProtoBuf.ProtoMember(6)]
        public bool bargainAppearStatus;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GUILD_LIST_VO> list = new System.Collections.Generic.List<I_GUILD_LIST_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_FIND
    {
        [ProtoBuf.ProtoMember(1)]
        public uint guildId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_FIND
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GUILD_LIST_VO> list = new System.Collections.Generic.List<I_GUILD_LIST_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_DISSOLVE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_DISSOLVE
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_CHANGE_NOTICE
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string notice = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_CHANGE_NOTICE
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string notice = "";

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_EDIT_APPLY_CONDITION
    {
        [ProtoBuf.ProtoMember(1)]
        public uint reviewType;

        [ProtoBuf.ProtoMember(2)]
        public uint memberLimitLevel;

        [ProtoBuf.ProtoMember(3)]
        public long memberLimitFighting;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_EDIT_APPLY_CONDITION
    {
        [ProtoBuf.ProtoMember(1)]
        public uint reviewType;

        [ProtoBuf.ProtoMember(2)]
        public uint memberLimitLevel;

        [ProtoBuf.ProtoMember(3)]
        public long memberLimitFighting;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public int guildId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public bool join;

        [ProtoBuf.ProtoMember(2)]
        public uint guildId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_APPLY_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_APPLY_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> list = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_APPLY_GUILD_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_APPLY_GUILD_LIST
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] guildIds;

        [ProtoBuf.ProtoMember(2)]
        public uint cdTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_DEAL_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public int targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint dealType;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_DEAL_APPLY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint dealType;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_BATCH_REFUSE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_BATCH_REFUSE
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KICK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KICK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_MODIFY_POWER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint powerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_MODIFY_POWER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint powerId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_QUIT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_QUIT
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_UPGRADE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint level;

        [ProtoBuf.ProtoMember(2)]
        public uint money;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_MONEY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_MONEY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<S_MESSAGE> messageList = new System.Collections.Generic.List<S_MESSAGE>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.common.I_USER_PROFILE> userInfos = new System.Collections.Generic.List<protobuf.common.I_USER_PROFILE>();

        [ProtoBuf.ProtoContract]
        public class S_MESSAGE
        {
            [ProtoBuf.ProtoMember(1)]
            public uint userId;

            [ProtoBuf.ProtoMember(2)]
            public uint position;

            [ProtoBuf.ProtoMember(3)]
            public uint type;

            [ProtoBuf.ProtoMember(4)]
            public uint cnt;

            [ProtoBuf.ProtoMember(5)]
            public uint targetId;

            [ProtoBuf.ProtoMember(6)]
            public uint operateTime;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_DONATE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint donateId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_DONATE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint cnt;

        [ProtoBuf.ProtoMember(2)]
        public uint donateId;

        [ProtoBuf.ProtoMember(3)]
        public uint guildDonate;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_DONATE_PROGRESS
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_DONATE_PROGRESS
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_GIFT_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_GIFT_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GIFT_VO> list = new System.Collections.Generic.List<I_GIFT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint gradientCnt;

        [ProtoBuf.ProtoContract]
        public class I_GIFT_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint id;

            [ProtoBuf.ProtoMember(2)]
            public bool draw;

            [ProtoBuf.ProtoMember(3)]
            public uint sendTime;

            [ProtoBuf.ProtoMember(4)]
            public uint itemId;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_GIFT_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string giftIds = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_GIFT_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GIFT_INFO_VO> list = new System.Collections.Generic.List<I_GIFT_INFO_VO>();

        [ProtoBuf.ProtoContract]
        public class I_GIFT_INFO_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public protobuf.common.I_USER_PROFILE userInfo;

            [ProtoBuf.ProtoMember(2)]
            public uint drawCnt;

            [ProtoBuf.ProtoMember(3)]
            public uint id;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_GIFT_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint giftId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_GIFT_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public uint giftId;

        [ProtoBuf.ProtoMember(2)]
        public uint drawCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint giftScore;

        [ProtoBuf.ProtoMember(4)]
        public uint rareNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_GIFT_GRADIENT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_GIFT_GRADIENT
    {
        [ProtoBuf.ProtoMember(2)]
        public uint gradientCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_HOUSE_VO> houseList = new System.Collections.Generic.List<I_HOUSE_VO>();

        [ProtoBuf.ProtoContract]
        public class I_HOUSE_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint id;

            [ProtoBuf.ProtoMember(2)]
            public uint unlockStatus;

            [ProtoBuf.ProtoMember(3)]
            public bool isPrevPeroid;

            [ProtoBuf.ProtoMember(4)]
            public System.Collections.Generic.Dictionary<ulong, ulong> extraReward = new System.Collections.Generic.Dictionary<ulong, ulong>();

            [ProtoBuf.ProtoMember(5)]
            public uint startTime;

            [ProtoBuf.ProtoMember(6)]
            public uint endTime;

            [ProtoBuf.ProtoMember(7)]
            public bool haveReward;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_ENABLE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_ENABLE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

        [ProtoBuf.ProtoMember(3)]
        public uint startTime;

        [ProtoBuf.ProtoMember(4)]
        public uint endTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_PLANT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(3)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class I_GUILD_PLANT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(3)]
        public uint pos;

        [ProtoBuf.ProtoMember(4)]
        public uint flowerLv;

        [ProtoBuf.ProtoMember(5)]
        public uint plantTime;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_PLANT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GUILD_PLANT_VO plant;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GUILD_PLANT_VO> plantList = new System.Collections.Generic.List<I_GUILD_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_DETAIL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_DETAIL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GUILD_PLANT_VO> plantList = new System.Collections.Generic.List<I_GUILD_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> flowerItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint houseId;

        [ProtoBuf.ProtoMember(4)]
        public uint startTime;

        [ProtoBuf.ProtoMember(5)]
        public uint endTime;

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.Dictionary<ulong, ulong> extraReward = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_HOUSE_MEMBERS
    {
        [ProtoBuf.ProtoMember(1)]
        public uint houseId;

        [ProtoBuf.ProtoMember(2)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_HOUSE_MEMBERS
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GUILD_MEMBER_PLANT_VO> memberPlantList = new System.Collections.Generic.List<I_GUILD_MEMBER_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint houseId;

        [ProtoBuf.ProtoContract]
        public class I_GUILD_MEMBER_PLANT_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public protobuf.common.I_USER_PROFILE userInfo;

            [ProtoBuf.ProtoMember(2)]
            public uint powerId;

            [ProtoBuf.ProtoMember(3)]
            public System.Collections.Generic.Dictionary<ulong, ulong> reward = new System.Collections.Generic.Dictionary<ulong, ulong>();

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KAN_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KAN_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint confId;

        [ProtoBuf.ProtoMember(2)]
        public bool haveKan;

        [ProtoBuf.ProtoMember(3)]
        public uint kanPrice;

        [ProtoBuf.ProtoMember(4)]
        public bool haveBuy;

        [ProtoBuf.ProtoMember(5)]
        public uint kanCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KAN
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KAN
    {
        [ProtoBuf.ProtoMember(1)]
        public uint kanPrice;

        [ProtoBuf.ProtoMember(2)]
        public uint mePrice;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KAN_DETAIL
    {
        [ProtoBuf.ProtoMember(1)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KAN_DETAIL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_KAN_VO> kanList = new System.Collections.Generic.List<I_KAN_VO>();

        [ProtoBuf.ProtoContract]
        public class I_KAN_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public protobuf.common.I_USER_PROFILE userInfo;

            [ProtoBuf.ProtoMember(2)]
            public uint kanPrice;

            [ProtoBuf.ProtoMember(3)]
            public uint time;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KAN_NOT
    {
        [ProtoBuf.ProtoMember(1)]
        public int page;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KAN_NOT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_NOT_KAN_VO> notKan = new System.Collections.Generic.List<I_NOT_KAN_VO>();

        [ProtoBuf.ProtoContract]
        public class I_NOT_KAN_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public protobuf.common.I_USER_PROFILE userInfo;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_KAN_BUY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_KAN_BUY
    {
        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_SHOP_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_SHOP_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<uint, uint> buyCntStat = new System.Collections.Generic.Dictionary<uint, uint>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_SHOP_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_SHOP_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public uint buyCnt;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
