// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: guildcompetition.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.guild
{
    [ProtoBuf.ProtoContract]
    public class I_COMPETITION_TASK_VO
    {
        [ProtoBuf.ProtoMember(2)]
        public uint pos;

        [ProtoBuf.ProtoMember(3)]
        public uint id;

        [ProtoBuf.ProtoMember(4)]
        public uint curCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint needItem;

        [ProtoBuf.ProtoMember(6)]
        public uint needCnt;

        [ProtoBuf.ProtoMember(7)]
        public uint receiveTime;

        [ProtoBuf.ProtoMember(8)]
        public uint receiveUserId;

        [ProtoBuf.ProtoMember(9)]
        public uint refreshTime;

        [ProtoBuf.ProtoMember(10)]
        public uint limitedTime;

        [ProtoBuf.ProtoMember(11)]
        public protobuf.common.I_USER_PROFILE userInfo;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public bool join;

        [ProtoBuf.ProtoMember(2)]
        public uint oddTaskCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint score;

        [ProtoBuf.ProtoMember(4)]
        public uint guildScore;

        [ProtoBuf.ProtoMember(5)]
        public uint matchLv;

        [ProtoBuf.ProtoMember(6)]
        public uint rankNum;

        [ProtoBuf.ProtoMember(7)]
        public System.Collections.Generic.List<I_COMPETITION_TASK_VO> taskList = new System.Collections.Generic.List<I_COMPETITION_TASK_VO>();

        [ProtoBuf.ProtoMember(8, IsPacked = true)]
        public uint[] specialFlowers;

        [ProtoBuf.ProtoMember(9)]
        public bool memberJoinStatus;

        [ProtoBuf.ProtoMember(10, IsPacked = true)]
        public uint[] rewardIds;

        [ProtoBuf.ProtoMember(11, IsPacked = true)]
        public uint[] selfRewardIds;

        [ProtoBuf.ProtoMember(12)]
        public uint endTime;

        [ProtoBuf.ProtoMember(13)]
        public uint startTime;

        [ProtoBuf.ProtoMember(14)]
        public System.Collections.Generic.List<string> resultStat = new System.Collections.Generic.List<string>();

        [ProtoBuf.ProtoMember(15)]
        public uint preRank;

        [ProtoBuf.ProtoMember(16)]
        public uint preGrade;

        [ProtoBuf.ProtoMember(17)]
        public uint taskCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_POS_TASK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_POS_TASK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public I_COMPETITION_TASK_VO taskList;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_RECEIVE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_RECEIVE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public I_COMPETITION_TASK_VO task;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_REFRESH
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_REFRESH
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public I_COMPETITION_TASK_VO task;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint id;

        [ProtoBuf.ProtoMember(3)]
        public uint score;

        [ProtoBuf.ProtoMember(4)]
        public I_COMPETITION_TASK_VO task;

        [ProtoBuf.ProtoMember(5)]
        public uint guildScore;

        [ProtoBuf.ProtoMember(6)]
        public uint taskCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_SELF_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_SELF_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_PROGRESS_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_PROGRESS_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class I_COMPETITION_GUILD_RANK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint rankNum;

        [ProtoBuf.ProtoMember(2)]
        public uint guildId;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string guildName = "";

        [ProtoBuf.ProtoMember(4)]
        public uint score;

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string flagId = "";

    }

    [ProtoBuf.ProtoContract]
    public class I_COMPETITION_MEMBER_RANK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint rankNum;

        [ProtoBuf.ProtoMember(2)]
        public uint userId;

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string userName = "";

        [ProtoBuf.ProtoMember(4)]
        public uint score;

        [ProtoBuf.ProtoMember(5)]
        public uint taskCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_GUILD_RANK
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_GUILD_RANK
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_COMPETITION_GUILD_RANK_VO> rankList = new System.Collections.Generic.List<I_COMPETITION_GUILD_RANK_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUILD_COMPETITION_MEMBER_RANK
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUILD_COMPETITION_MEMBER_RANK
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_COMPETITION_MEMBER_RANK_VO> rankList = new System.Collections.Generic.List<I_COMPETITION_MEMBER_RANK_VO>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
