// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ikebana.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.ikebana
{
    [ProtoBuf.ProtoContract]
    public class I_VASE_REWARD_STATUS
    {
        [ProtoBuf.ProtoMember(1)]
        public uint status;

        [ProtoBuf.ProtoMember(2)]
        public uint shareStatus;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_IKEBANA_MAKE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint combinationId;

        [ProtoBuf.ProtoMember(2)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_IKEBANA_MAKE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint combinationId;

        [ProtoBuf.ProtoMember(2)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VASE_REWARD_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VASE_REWARD_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS> vaseRewardInfo = new System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VASE_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VASE_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VASE_FLOWER_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint vaseId;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VASE_FLOWER_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint vaseId;

        [ProtoBuf.ProtoMember(3)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VASE_GATHER_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VASE_GATHER_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VASE_ONEKEY_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VASE_ONEKEY_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS> vaseRewardInfo = new System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS>();

        [ProtoBuf.ProtoMember(3)]
        public uint vaseId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_IKEBANA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint combinationId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_IKEBANA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS> vaseRewardInfo = new System.Collections.Generic.Dictionary<uint, I_VASE_REWARD_STATUS>();

        [ProtoBuf.ProtoMember(3)]
        public uint combinationId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
