// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: illustrated.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.illustrated
{
    [ProtoBuf.ProtoContract]
    public class I_ILLUSTRATED_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public uint unlockReward;

        [ProtoBuf.ProtoMember(3)]
        public uint levelReward;

        [ProtoBuf.ProtoMember(4)]
        public uint gradeReward;

    }

    [ProtoBuf.ProtoContract]
    public class I_ILLUSTRATED_INFO_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint collectValue;

        [ProtoBuf.ProtoMember(2)]
        public uint collectLevel;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ILLUSTRATED_GETCOLLECT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public uint itemType;

        [ProtoBuf.ProtoMember(3)]
        public uint collectType;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ILLUSTRATED_GETCOLLECT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint collectValue;

        [ProtoBuf.ProtoMember(2)]
        public I_ILLUSTRATED_VO illustratedVo;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ILLUSTRATED_UPGRADELEVEL
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ILLUSTRATED_UPGRADELEVEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint collectLevel;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
