// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: item.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.item
{
    [ProtoBuf.ProtoContract]
    public class I_ITEM_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong itemDefId;

        [ProtoBuf.ProtoMember(2)]
        public ulong count;

    }

    [ProtoBuf.ProtoContract]
    public class I_ITEMS
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_EXCHANGE_FLOWER_CARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_EXCHANGE_FLOWER_CARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
