// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: login.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.login
{
    [ProtoBuf.ProtoContract]
    public class I_PROGRESS_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public uint progress;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] rewardId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_LOGIN
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string platformId = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_LOGIN
    {
        [ProtoBuf.ProtoMember(1)]
        public long userId;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string token = "";

        [ProtoBuf.ProtoMember(3)]
        public bool isRegister;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string gameWssUrl = "";

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string chatWssUrl = "";

        [ProtoBuf.ProtoMember(6)]
        public uint serverTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GAMEINIT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GAMEINIT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<protobuf.plant.I_PLANT_VO> plantList = new System.Collections.Generic.List<protobuf.plant.I_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.table.I_TABLE_VO> tableList = new System.Collections.Generic.List<protobuf.table.I_TABLE_VO>();

        [ProtoBuf.ProtoMember(3)]
        public protobuf.user.I_PROFILE_VO profile;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<protobuf.user.I_PROFILE_INFO_VO> profileInfos = new System.Collections.Generic.List<protobuf.user.I_PROFILE_INFO_VO>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.user.I_PROFILE_TIME_INFO_VO> dynamicInfo = new System.Collections.Generic.List<protobuf.user.I_PROFILE_TIME_INFO_VO>();

        [ProtoBuf.ProtoMember(6)]
        public protobuf.user.I_BEHAVIORDAILY_VO behaviorDaily;

        [ProtoBuf.ProtoMember(7)]
        public uint npcOrderRefreshTime;

        [ProtoBuf.ProtoMember(8)]
        public System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO> npcOrderOldList = new System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO>();

        [ProtoBuf.ProtoMember(9)]
        public System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO> npcOrderNewList = new System.Collections.Generic.List<protobuf.npcorder.I_NPCORDER_VO>();

        [ProtoBuf.ProtoMember(10)]
        public System.Collections.Generic.List<protobuf.item.I_ITEM_VO> itemList = new System.Collections.Generic.List<protobuf.item.I_ITEM_VO>();

        [ProtoBuf.ProtoMember(11)]
        public System.Collections.Generic.List<protobuf.order.I_ORDER_VO> orderList = new System.Collections.Generic.List<protobuf.order.I_ORDER_VO>();

        [ProtoBuf.ProtoMember(12)]
        public System.Collections.Generic.List<protobuf.plant.I_PLANT_SEED_VO> seedList = new System.Collections.Generic.List<protobuf.plant.I_PLANT_SEED_VO>();

        [ProtoBuf.ProtoMember(13)]
        public uint serverTime;

        [ProtoBuf.ProtoMember(14)]
        public uint userId;

        [ProtoBuf.ProtoMember(15)]
        public protobuf.dress.S_MSG_DRESS_INFO dress;

        [ProtoBuf.ProtoMember(16)]
        public protobuf.floristshop.S_MSG_FLORIST_INFO floristShopInfo;

        [ProtoBuf.ProtoMember(17)]
        public MAINTASK_VO mainTask;

        [ProtoBuf.ProtoMember(18)]
        public System.Collections.Generic.List<I_PROGRESS_VO> progress = new System.Collections.Generic.List<I_PROGRESS_VO>();

        [ProtoBuf.ProtoMember(19)]
        public protobuf.welfare.S_MSG_WELFARE_INFO welfareInfo;

        [ProtoBuf.ProtoMember(20)]
        public protobuf.misc.I_DAILY_LOGIN dailyLoginInfo;

        [ProtoBuf.ProtoMember(21)]
        public bool isTodayFirstLogin;

        [ProtoBuf.ProtoMember(22)]
        public System.Collections.Generic.List<protobuf.reddot.I_REDDOT_VO> reddot = new System.Collections.Generic.List<protobuf.reddot.I_REDDOT_VO>();

        [ProtoBuf.ProtoMember(23)]
        public System.Collections.Generic.List<protobuf.rob.I_ROB_ARREST_VO> arrestList = new System.Collections.Generic.List<protobuf.rob.I_ROB_ARREST_VO>();

        [ProtoBuf.ProtoContract]
        public class MAINTASK_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint mainTaskId;

            [ProtoBuf.ProtoMember(2)]
            public uint mainTaskCnt;

            [ProtoBuf.ProtoMember(3)]
            public uint rookieTaskTime;

            [ProtoBuf.ProtoMember(4, IsPacked = true)]
            public uint[] rookieRewards;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GAME_MISC
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GAME_MISC
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.recharge.S_MSG_RECHARGE_INFO rechargeInfo;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.recharge.I_GIFTPACK_VO> giftPackList = new System.Collections.Generic.List<protobuf.recharge.I_GIFTPACK_VO>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<protobuf.recharge.I_TOUR_VO> tourList = new System.Collections.Generic.List<protobuf.recharge.I_TOUR_VO>();

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<protobuf.video.I_VIDEO_VO> videoWatch = new System.Collections.Generic.List<protobuf.video.I_VIDEO_VO>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.mapevent.I_MAPEVENT_VO> mapEventList = new System.Collections.Generic.List<protobuf.mapevent.I_MAPEVENT_VO>();

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.List<protobuf.fund.I_FUND_VO> fundInfo = new System.Collections.Generic.List<protobuf.fund.I_FUND_VO>();

        [ProtoBuf.ProtoMember(7)]
        public protobuf.plant.I_CULTIVATE_VO cultivate;

        [ProtoBuf.ProtoMember(8)]
        [System.ComponentModel.DefaultValue("")]
        public string guildName = "";

        [ProtoBuf.ProtoMember(9)]
        public System.Collections.Generic.List<protobuf.guild.I_BRIEF_MEMBER_VO> guildMembers = new System.Collections.Generic.List<protobuf.guild.I_BRIEF_MEMBER_VO>();

        [ProtoBuf.ProtoMember(10)]
        public System.Collections.Generic.List<protobuf.reddot.I_REDDOT_VO> reddot = new System.Collections.Generic.List<protobuf.reddot.I_REDDOT_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GAME_CROSS_DAY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GAME_CROSS_DAY
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.user.I_BEHAVIORDAILY_VO behaviorDaily;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_PROGRESS_VO> progress = new System.Collections.Generic.List<I_PROGRESS_VO>();

        [ProtoBuf.ProtoMember(3)]
        public protobuf.recharge.S_MSG_RECHARGE_INFO rechargeInfo;

        [ProtoBuf.ProtoMember(4)]
        public protobuf.misc.I_DAILY_LOGIN dailyLoginInfo;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.video.I_VIDEO_VO> videoWatch = new System.Collections.Generic.List<protobuf.video.I_VIDEO_VO>();

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT> furnitureExchangeStat = new System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT>();

        [ProtoBuf.ProtoMember(7)]
        public bool isTodayFirstLogin;

        [ProtoBuf.ProtoMember(8)]
        public protobuf.dailyTask.S_MSG_DAILY_TASK dailyTaskInfo;

        [ProtoBuf.ProtoMember(9)]
        public System.Collections.Generic.List<protobuf.dailyTask.I_ACHIEV_TASK_VO> achievTaskList = new System.Collections.Generic.List<protobuf.dailyTask.I_ACHIEV_TASK_VO>();

        [ProtoBuf.ProtoMember(10)]
        public System.Collections.Generic.List<protobuf.order.I_ORDER_VO> orderList = new System.Collections.Generic.List<protobuf.order.I_ORDER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GAME_MILD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GAME_MILD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<uint, protobuf.ikebana.I_VASE_REWARD_STATUS> vaseRewardInfo = new System.Collections.Generic.Dictionary<uint, protobuf.ikebana.I_VASE_REWARD_STATUS>();

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] blackUserIds;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT> furnitureExchangeStat = new System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT>();

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<protobuf.common.I_NOTICE_VO> notice = new System.Collections.Generic.List<protobuf.common.I_NOTICE_VO>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.mail.I_MAIL_VO> mailList = new System.Collections.Generic.List<protobuf.mail.I_MAIL_VO>();

        [ProtoBuf.ProtoMember(6, IsPacked = true)]
        public uint[] clickItems;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DELETE_ACCOUNT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DELETE_ACCOUNT
    {
    }

}

#pragma warning restore CS1591, CS0612, CS3021
