// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: lolita.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.monster
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_LOLITA_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_LOLITA_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_LOLI_TASK> loliTask = new System.Collections.Generic.List<I_LOLI_TASK>();

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] rewardIds;

        [ProtoBuf.ProtoContract]
        public class I_LOLI_TASK
        {
            [ProtoBuf.ProtoMember(1)]
            public uint id;

            [ProtoBuf.ProtoMember(2)]
            public uint curCnt;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_LOLITA_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint exchangeId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_LOLITA_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint exchangeId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_LOLITA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_LOLITA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
