// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mail.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.plant
{
    [ProtoBuf.ProtoContract]
    public class I_MAIL_VO
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string mailId = "";

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string title1 = "";

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string title2 = "";

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string title3 = "";

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<ulong, uint> reward = new System.Collections.Generic.Dictionary<ulong, uint>();

        [ProtoBuf.ProtoMember(6)]
        public uint status;

        [ProtoBuf.ProtoMember(7)]
        public uint createTime;

        [ProtoBuf.ProtoMember(8)]
        public System.Collections.Generic.List<string> @params = new System.Collections.Generic.List<string>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAIL_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAIL_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MAIL_VO> mailList = new System.Collections.Generic.List<I_MAIL_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAIL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<string> mailIds = new System.Collections.Generic.List<string>();

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAIL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<string> mailIds = new System.Collections.Generic.List<string>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAIL_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<string> mailIds = new System.Collections.Generic.List<string>();

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAIL_DEL
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<string> mailIds = new System.Collections.Generic.List<string>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
