// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mapevent.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.mapevent
{
    [ProtoBuf.ProtoContract]
    public class I_MAPEVENT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint eventId;

        [ProtoBuf.ProtoMember(3)]
        public uint coordinateId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRIGGER_MAPEVENT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint eventId;

        [ProtoBuf.ProtoMember(2)]
        public uint coordinateId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRIGGER_MAPEVENT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_MAPEVENT_VO mapEvent;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MAPEVENT_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MAPEVENT_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_MAPEVENT_VO mapEvent;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
