// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: misc.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.misc
{
    [ProtoBuf.ProtoContract]
    public class I_DAILY_LOGIN
    {
        [ProtoBuf.ProtoMember(1)]
        public uint currentDay;

        [ProtoBuf.ProtoMember(2)]
        public bool todayHaveDraw;

        [ProtoBuf.ProtoMember(3)]
        public uint status;

        [ProtoBuf.ProtoMember(4)]
        public uint currentSignDay;

        [ProtoBuf.ProtoMember(5)]
        public uint signDay;

        [ProtoBuf.ProtoMember(6)]
        public uint retroactiveDays;

        [ProtoBuf.ProtoMember(7)]
        public bool isSign;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_LOGIN_AWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_LOGIN_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_SIGN
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_SIGN
    {
        [ProtoBuf.ProtoMember(1)]
        public uint signDay;

        [ProtoBuf.ProtoMember(2)]
        public bool isSign;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_RETROACTIVE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_RETROACTIVE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint signDay;

        [ProtoBuf.ProtoMember(2)]
        public uint retroactiveDays;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VIDEO_WATCH
    {
        [ProtoBuf.ProtoMember(1)]
        public uint videoId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VIDEO_WATCH
    {
        [ProtoBuf.ProtoMember(1)]
        public uint videoId;

        [ProtoBuf.ProtoMember(2)]
        public uint watchCount;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GUIDE
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string step = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GUIDE
    {
    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MONTH_CARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MONTH_CARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class I_USER_INFO_DRESS_GUILD
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public protobuf.dress.I_DRESS_INFO dress;

        [ProtoBuf.ProtoMember(3)]
        public I_GUILD_VO guildInfo;

        [ProtoBuf.ProtoContract]
        public class I_GUILD_VO
        {
            [ProtoBuf.ProtoMember(1)]
            [System.ComponentModel.DefaultValue("")]
            public string guildName = "";

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_BATCH_USERINFO_GUILD_DRESS
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] userIds;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

        [ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] withClosethUserIds;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.List<string> otherModules = new System.Collections.Generic.List<string>();

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_BATCH_USERINFO_GUILD_DRESS
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_USER_INFO_DRESS_GUILD> userList = new System.Collections.Generic.List<I_USER_INFO_DRESS_GUILD>();

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_UNLOCK_SYSTEM_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_UNLOCK_SYSTEM_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CHAPTER_PLOT_WATCH
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CHAPTER_PLOT_WATCH
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        [System.ComponentModel.DefaultValue("")]
        public string chapterPlot = "";

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_LOVE_FLOWER_ART
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string loveFlowerArt = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_LOVE_FLOWER_ART
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string loveFlowerArt = "";

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GET_MODULE_POWER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint moduleId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GET_MODULE_POWER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint moduleId;

        [ProtoBuf.ProtoMember(2)]
        public uint drawingPower;

    }

    [ProtoBuf.ProtoContract]
    public class I_DAILY_STAT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint date;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_SINGLE_STAT> stat = new System.Collections.Generic.List<I_SINGLE_STAT>();

        [ProtoBuf.ProtoContract]
        public class I_SINGLE_STAT
        {
            [ProtoBuf.ProtoMember(1)]
            public uint type;

            [ProtoBuf.ProtoMember(2)]
            public uint cnt;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DAILY_MANAGER_STAT
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DAILY_MANAGER_STAT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_DAILY_STAT> data = new System.Collections.Generic.List<I_DAILY_STAT>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TURNTABLE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TURNTABLE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_OPEN_GIFT_PACK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

        [ProtoBuf.ProtoMember(2)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_OPEN_GIFT_PACK
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_OTHER_USER_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint otherUserId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_OTHER_USER_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public protobuf.dress.I_DRESS_INFO dress;

        [ProtoBuf.ProtoMember(3)]
        public I_GUILD_VO guildInfo;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string loveFlowerArt = "";

        [ProtoBuf.ProtoMember(5)]
        public uint flowerCnt;

        [ProtoBuf.ProtoMember(6)]
        public uint makeIkebanaCnt;

        [ProtoBuf.ProtoMember(7)]
        public uint suitCollectCnt;

        [ProtoBuf.ProtoMember(8)]
        public bool isFriend;

        [ProtoBuf.ProtoMember(9)]
        public bool isApply;

        [ProtoBuf.ProtoMember(10)]
        public bool isVip;

        [ProtoBuf.ProtoMember(11)]
        public uint exp;

        [ProtoBuf.ProtoContract]
        public class I_GUILD_VO
        {
            [ProtoBuf.ProtoMember(1)]
            [System.ComponentModel.DefaultValue("")]
            public string guildName = "";

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GIFT_CODE
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string code = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GIFT_CODE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
