// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: monster.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.monster
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_MONSTER_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint monsterId;

        [ProtoBuf.ProtoMember(2)]
        public uint monsterUid;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MONSTER_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint monsterCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint monsterUid;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
