// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: notify.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.notify
{
    [ProtoBuf.ProtoContract]
    public class S_SYSTEM_ITEM_NOTIFY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<protobuf.user.I_PROFILE_TIME_INFO_VO> dynamicInfo = new System.Collections.Generic.List<protobuf.user.I_PROFILE_TIME_INFO_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class S_SYSTEM_EVENT_NOTIFY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint eventType;

        [ProtoBuf.ProtoMember(2)]
        public ulong ext1;

        [ProtoBuf.ProtoMember(3)]
        public ulong ext2;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string ext3 = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_SYSTEM_EVENT_MARQUEE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string ext1 = "";

        [ProtoBuf.ProtoMember(3)]
        public ulong ext2;

        [ProtoBuf.ProtoMember(4)]
        public ulong ext3;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
