// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: npc.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.npc
{
    [ProtoBuf.ProtoContract]
    public class I_NPC_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint npcId;

        [ProtoBuf.ProtoMember(2)]
        public uint level;

        [ProtoBuf.ProtoMember(3)]
        public uint exp;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] levelRewards;

    }

    [ProtoBuf.ProtoContract]
    public class I_NPC_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_NPC_VO> npcList = new System.Collections.Generic.List<I_NPC_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint surplusGiveGiftCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint surplusGiveIkebanaCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint buyGiftCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint buyIkebanaCnt;

        [ProtoBuf.ProtoMember(6)]
        public uint totalLevel;

        [ProtoBuf.ProtoMember(7)]
        public uint totalExp;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_NPC_GIVE_GIFT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint npcId;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

        [ProtoBuf.ProtoMember(3)]
        public uint itemId;

        [ProtoBuf.ProtoMember(4)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_NPC_GIVE_GIFT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_NPC_VO npc;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint surplusGiveGiftCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint surplusGiveIkebanaCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint totalLevel;

        [ProtoBuf.ProtoMember(6)]
        public uint totalExp;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_NPC_BUY_GIVE_CNT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_NPC_BUY_GIVE_CNT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint surplusGiveGiftCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint surplusGiveIkebanaCnt;

        [ProtoBuf.ProtoMember(5)]
        public uint buyGiftCnt;

        [ProtoBuf.ProtoMember(6)]
        public uint buyIkebanaCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_NPC_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint npcId;

        [ProtoBuf.ProtoMember(2)]
        public uint rewardLevel;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_NPC_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint npcId;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] levelRewards;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
