// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: npcorder.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.npcorder
{
    [ProtoBuf.ProtoContract]
    public class I_NPCORDER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

        [ProtoBuf.ProtoMember(2)]
        public uint orderId;

        [ProtoBuf.ProtoMember(3)]
        public uint ratio;

        [ProtoBuf.ProtoMember(4)]
        public uint npc;

        [ProtoBuf.ProtoMember(5)]
        public uint isDouble;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_NPCORDER_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_NPCORDER_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public long npcOrderRefreshTime;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_NPCORDER_VO> npcOrderOldList = new System.Collections.Generic.List<I_NPCORDER_VO>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_NPCORDER_VO> npcOrderNewList = new System.Collections.Generic.List<I_NPCORDER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_NPCORDER_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_NPCORDER_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public long npcOrderRefreshTime;

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

        [ProtoBuf.ProtoMember(3)]
        public uint type;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
