// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: order.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.order
{
    [ProtoBuf.ProtoContract]
    public class I_ORDER_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint orderType;

        [ProtoBuf.ProtoMember(3)]
        public int status;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> needItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<ulong, ulong> reward = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(8)]
        public uint cdTime;

        [ProtoBuf.ProtoMember(9)]
        public uint isDouble;

        [ProtoBuf.ProtoMember(10)]
        public bool isExpAddtion;

        [ProtoBuf.ProtoMember(11)]
        public bool isGoldAddtion;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ORDER_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ORDER_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ORDER_VO> orderList = new System.Collections.Generic.List<I_ORDER_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ORDER_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ORDER_SUBMIT
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ORDER_VO order;

        [ProtoBuf.ProtoMember(2)]
        public uint orderCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint position;

        [ProtoBuf.ProtoMember(4)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ORDER_VIDEO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ORDER_VIDEO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ORDER_DAILY_MISSION_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint treasureChest;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ORDER_DAILY_MISSION_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string orderStageAward = "";

    }

}

#pragma warning restore CS1591, CS0612, CS3021
