// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: pets.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.pets
{
    [ProtoBuf.ProtoContract]
    public class I_PETS_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint petId;

        [ProtoBuf.ProtoMember(2)]
        public uint exp;

        [ProtoBuf.ProtoMember(3)]
        public int level;

        [ProtoBuf.ProtoMember(4)]
        public int starLevel;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PETS_VO> pets = new System.Collections.Generic.List<I_PETS_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_DRAW
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ITEM_VO> items = new System.Collections.Generic.List<I_ITEM_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_PETS_VO> pets = new System.Collections.Generic.List<I_PETS_VO>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoContract]
        public class I_ITEM_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public ulong itemId;

            [ProtoBuf.ProtoMember(2)]
            public ulong num;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint petId;

        [ProtoBuf.ProtoMember(2)]
        public ulong itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PETS_VO pet;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_UPGRADE_LEVEL
    {
        [ProtoBuf.ProtoMember(1)]
        public uint petId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_UPGRADE_LEVEL
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PETS_VO pet;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_STAR
    {
        [ProtoBuf.ProtoMember(1)]
        public uint petId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_STAR
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PETS_VO pet;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PET_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint petId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PET_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PETS_VO pet;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> costItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
