// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: plant.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.plant
{
    [ProtoBuf.ProtoContract]
    public class I_PLANT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint decorId;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(3)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(4)]
        public uint status;

        [ProtoBuf.ProtoMember(5)]
        public uint harvestCount;

        [ProtoBuf.ProtoMember(6)]
        public uint level;

        [ProtoBuf.ProtoMember(7)]
        public int isAppearFairy;

    }

    [ProtoBuf.ProtoContract]
    public class I_PLANT_STEAL_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint decorId;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(3)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(4)]
        public uint status;

        [ProtoBuf.ProtoMember(5)]
        public uint harvestCount;

        [ProtoBuf.ProtoMember(6)]
        public uint level;

        [ProtoBuf.ProtoMember(7)]
        public System.Collections.Generic.Dictionary<uint, uint> stealInfo = new System.Collections.Generic.Dictionary<uint, uint>();

        [ProtoBuf.ProtoMember(8)]
        public int isAppearFairy;

    }

    [ProtoBuf.ProtoContract]
    public class I_CULTIVATE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(3)]
        public uint videoTimes;

        [ProtoBuf.ProtoMember(4)]
        public uint helpCnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_PLANT_SEED_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public uint level;

        [ProtoBuf.ProtoMember(3)]
        public uint breakLv;

        [ProtoBuf.ProtoMember(4)]
        public uint gradeLv;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_PLANT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_PLANT
    {
        [ProtoBuf.ProtoMember(1)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_HARVEST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PLANT_SEED_VO seed;

        [ProtoBuf.ProtoMember(2)]
        public I_CULTIVATE_VO cultivate;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_SPEEDUP
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_SPEEDUP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint harvestTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_VIDEO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_VIDEO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(2)]
        public uint videoTimes;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_HELP
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_HELP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(2)]
        public uint helpCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_CULTIVATE_REPAIR
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_CULTIVATE_REPAIR
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_PLANT
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

        [ProtoBuf.ProtoMember(2)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_PLANT
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint todayHavePlotCnt;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_WATER
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_WATER
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint personalGoalActNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_SPEED
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_SPEED
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_FREE_SPEEDUP
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_FREE_SPEEDUP
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VIDEO_PLANT_SPEED
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VIDEO_PLANT_SPEED
    {
        [ProtoBuf.ProtoMember(1)]
        public uint videoId;

        [ProtoBuf.ProtoMember(2)]
        public uint watchCount;

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_HARVEST
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_HARVEST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint personalGoalActNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PLANT_VO plant;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SEED_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SEED_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PLANT_SEED_VO seed;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SEED_UPGRADE_BREAKLV
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SEED_UPGRADE_BREAKLV
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PLANT_SEED_VO seed;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SEED_UPGRADE_GRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint flowerId;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SEED_UPGRADE_GRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_PLANT_SEED_VO seed;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLANT_MOVE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] decorIds;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLANT_MOVE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_PLANT_VO> plantList = new System.Collections.Generic.List<I_PLANT_VO>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
