// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: rank.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.plant
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_RANK_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_RANK_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public I_MY_RANK myRank;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_RANK_VO> rankList = new System.Collections.Generic.List<I_RANK_VO>();

        [ProtoBuf.ProtoMember(3)]
        public uint type;

        [ProtoBuf.ProtoContract]
        public class I_MY_RANK
        {
            [ProtoBuf.ProtoMember(1)]
            public uint rank;

            [ProtoBuf.ProtoMember(2)]
            public uint score;

        }

        [ProtoBuf.ProtoContract]
        public class I_RANK_VO
        {
            [ProtoBuf.ProtoMember(1)]
            public uint rank;

            [ProtoBuf.ProtoMember(2)]
            public uint targetId;

            [ProtoBuf.ProtoMember(3)]
            public uint score;

        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021
