// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: recharge.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.recharge
{
    [ProtoBuf.ProtoContract]
    public class I_GIFTPACK_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public uint endTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_TOUR_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint tourId;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] rewardIds;

        [ProtoBuf.ProtoMember(3)]
        public uint buyCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_GIFT_PACK_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_GIFT_PACK_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GIFTPACK_VO> giftPackList = new System.Collections.Generic.List<I_GIFTPACK_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.List<I_TOUR_VO> tourList = new System.Collections.Generic.List<I_TOUR_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TOUR_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint tourId;

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TOUR_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] rewardIds;

        [ProtoBuf.ProtoMember(3)]
        public uint tourId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PLACE_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        public uint payConfType;

        [ProtoBuf.ProtoMember(2)]
        public uint payDefId;

        [ProtoBuf.ProtoMember(3)]
        public uint osType;

        [ProtoBuf.ProtoMember(4)]
        public uint payType;

        [ProtoBuf.ProtoMember(5)]
        public uint platformType;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PLACE_ORDER
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string orderNo = "";

        [ProtoBuf.ProtoMember(2)]
        public uint price;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_DELIVER
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string orderNo = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_DELIVER
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint payConfType;

        [ProtoBuf.ProtoMember(3)]
        public uint payDefId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ACC_RECHARGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ACC_RECHARGE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] rechargeRewards;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_FIRST_RECHARGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint dayNum;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_FIRST_RECHARGE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] firstRechargeRewards;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_RECHARGE_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_RECHARGE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint rechargeAmount;

        [ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] rechargeRwards;

        [ProtoBuf.ProtoMember(3)]
        public uint firstRechargeTime;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] firstRechargeRewards;

        [ProtoBuf.ProtoMember(5)]
        public GAME_PAY_VO gamePay;

        [ProtoBuf.ProtoMember(6)]
        public System.Collections.Generic.Dictionary<uint, uint> haveDiamondValue = new System.Collections.Generic.Dictionary<uint, uint>();

        [ProtoBuf.ProtoMember(7, IsPacked = true)]
        public uint[] haveGiftPack;

        [ProtoBuf.ProtoMember(8)]
        public System.Collections.Generic.Dictionary<uint, uint> haveMall = new System.Collections.Generic.Dictionary<uint, uint>();

        [ProtoBuf.ProtoContract]
        public class GAME_PAY_VO
        {
            [ProtoBuf.ProtoMember(1, IsPacked = true)]
            public uint[] buyIds;

            [ProtoBuf.ProtoMember(2)]
            public uint threeBuyId;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_RECHARGE_FREE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint payConfType;

        [ProtoBuf.ProtoMember(2)]
        public uint payDefId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_RECHARGE_FREE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint payConfType;

        [ProtoBuf.ProtoMember(3)]
        public uint payDefId;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
