// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: reddot.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.reddot
{
    [ProtoBuf.ProtoContract]
    public class I_REDDOT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public bool redDot;

        [ProtoBuf.ProtoMember(3)]
        public uint ext1;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
