// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: rob.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.rob
{
    [ProtoBuf.ProtoContract]
    public class I_ROB_ARREST_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint arrestUserId;

        [ProtoBuf.ProtoMember(3)]
        public uint acquittalTime;

        [ProtoBuf.ProtoMember(4)]
        public protobuf.common.I_USER_PROFILE userInfo;

    }

    [ProtoBuf.ProtoContract]
    public class I_ROB_INFO_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint dailyRewardStatus;

        [ProtoBuf.ProtoMember(2)]
        public uint openShield;

    }

    [ProtoBuf.ProtoContract]
    public class I_ROB_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint robMasterUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint robAcquittalTime;

        [ProtoBuf.ProtoMember(3)]
        public uint robGuardTime;

    }

    [ProtoBuf.ProtoContract]
    public class I_ROB_MESSAGE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public bool isShield;

        [ProtoBuf.ProtoMember(2)]
        public bool arrestResult;

        [ProtoBuf.ProtoMember(3)]
        public uint operateTime;

        [ProtoBuf.ProtoMember(4)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(5)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(6)]
        public I_ROB_VO robInfo;

    }

    [ProtoBuf.ProtoContract]
    public class I_FRIEND_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.common.I_USER_PROFILE userInfo;

        [ProtoBuf.ProtoMember(2)]
        public I_ROB_VO robInfo;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ROB_ARREST_VO> arrestList = new System.Collections.Generic.List<I_ROB_ARREST_VO>();

        [ProtoBuf.ProtoMember(2)]
        public I_ROB_INFO_VO info;

        [ProtoBuf.ProtoMember(3)]
        public I_ROB_VO robInfo;

        [ProtoBuf.ProtoMember(4)]
        public protobuf.common.I_USER_PROFILE targetUserInfo;

        [ProtoBuf.ProtoMember(5)]
        public System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT> exchangeStat = new System.Collections.Generic.List<protobuf.commonActivity.I_EXCHANGE_STAT>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_DAILY_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_DAILY_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ROB_INFO_VO info;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

        [ProtoBuf.ProtoMember(2)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ROB_ARREST_VO arrest;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_SETSHIELD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_SETSHIELD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ROB_INFO_VO info;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_ARREST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_ARREST
    {
        [ProtoBuf.ProtoMember(1)]
        public bool isShield;

        [ProtoBuf.ProtoMember(2)]
        public bool arrestResult;

        [ProtoBuf.ProtoMember(3)]
        public I_ROB_ARREST_VO arrest;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_MESSAGE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_MESSAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_ROB_MESSAGE_VO> messageList = new System.Collections.Generic.List<I_ROB_MESSAGE_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_ENEMY_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_ENEMY_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FRIEND_VO> enemyList = new System.Collections.Generic.List<I_FRIEND_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_RECOMMEND_LIST
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_RECOMMEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FRIEND_VO> recommendList = new System.Collections.Generic.List<I_FRIEND_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public uint start;

        [ProtoBuf.ProtoMember(2)]
        public uint end;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_FRIEND_LIST
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_FRIEND_VO> friendList = new System.Collections.Generic.List<I_FRIEND_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint count;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_ROB_ARREST_VO arrest;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public uint indexId;

        [ProtoBuf.ProtoMember(4)]
        public uint gainsBonus;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_EXCHANGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

        [ProtoBuf.ProtoMember(2)]
        public uint num;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_ROB_SHOPBUY
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_ROB_SHOPBUY
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public protobuf.commonActivity.I_EXCHANGE_STAT exchange;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
