// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: share.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.share
{
    [ProtoBuf.ProtoContract]
    public class C_MSG_SHARE_LEVEL_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SHARE_LEVEL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SHARE_IKEBANA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint combinationId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SHARE_IKEBANA_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<uint, protobuf.ikebana.I_VASE_REWARD_STATUS> vaseRewardInfo = new System.Collections.Generic.Dictionary<uint, protobuf.ikebana.I_VASE_REWARD_STATUS>();

        [ProtoBuf.ProtoMember(3)]
        public uint combinationId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SHARE_FLOWER_REWARD
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SHARE_FLOWER_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
