// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: table.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.table
{
    [ProtoBuf.ProtoContract]
    public class I_TABLE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint gridId;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint count;

        [ProtoBuf.ProtoMember(4)]
        public uint harvestTime;

        [ProtoBuf.ProtoMember(5)]
        public uint expBuff;

        [ProtoBuf.ProtoMember(6)]
        public uint goldBuff;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TABLE_ONSHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public uint gridId;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint cnt;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TABLE_ONSHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public I_TABLE_VO table;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint costCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TABLE_SELL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint gridId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TABLE_SELL_REWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public I_TABLE_VO table;

        [ProtoBuf.ProtoMember(2)]
        public uint personalGoalActNum;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TABLE_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint gridId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TABLE_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public I_TABLE_VO table;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TABLE_ONEKEY_ONSHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TABLE_ONEKEY_ONSHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_TABLE_VO> tableList = new System.Collections.Generic.List<I_TABLE_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint costCnt;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
