// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: trade.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.friend
{
    [ProtoBuf.ProtoContract]
    public class I_GRID_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint shelfCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint buyCnt;

        [ProtoBuf.ProtoMember(4)]
        public uint price;

        [ProtoBuf.ProtoMember(5)]
        public uint itemId;

        [ProtoBuf.ProtoMember(6)]
        public uint num;

        [ProtoBuf.ProtoMember(7)]
        [System.ComponentModel.DefaultValue("")]
        public string password = "";

        [ProtoBuf.ProtoMember(8)]
        public uint shelfTime;

        [ProtoBuf.ProtoMember(9)]
        public uint sellStatus;

    }

    [ProtoBuf.ProtoContract]
    public class I_FRIEND_GRID_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint price;

        [ProtoBuf.ProtoMember(3)]
        public uint itemId;

        [ProtoBuf.ProtoMember(4)]
        public uint num;

        [ProtoBuf.ProtoMember(5)]
        public bool setPassword;

        [ProtoBuf.ProtoMember(6)]
        public uint shelfTime;

        [ProtoBuf.ProtoMember(7)]
        public uint sellStatus;

    }

    [ProtoBuf.ProtoContract]
    public class I_MESSAGE_LOG
    {
        [ProtoBuf.ProtoMember(1)]
        public uint price;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint num;

        [ProtoBuf.ProtoMember(4)]
        public uint operateTime;

        [ProtoBuf.ProtoMember(5)]
        public protobuf.common.I_USER_PROFILE userInfo;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_INFORMATION
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_INFORMATION
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_GRID_VO> grids = new System.Collections.Generic.List<I_GRID_VO>();

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(3)]
        public System.Collections.Generic.Dictionary<ulong, ulong> backItems = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(4)]
        public uint tradeGoldCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_FRIEND_SHOP
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_FRIEND_SHOP
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<FRINED_SHOP> friendGrids = new System.Collections.Generic.List<FRINED_SHOP>();

        [ProtoBuf.ProtoContract]
        public class FRINED_SHOP
        {
            [ProtoBuf.ProtoMember(1)]
            public System.Collections.Generic.List<I_FRIEND_GRID_VO> grids = new System.Collections.Generic.List<I_FRIEND_GRID_VO>();

            [ProtoBuf.ProtoMember(2)]
            public protobuf.common.I_USER_PROFILE userInfo;

        }

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_UPPER_SHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint itemId;

        [ProtoBuf.ProtoMember(3)]
        public uint num;

        [ProtoBuf.ProtoMember(4)]
        public uint price;

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string password = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_UPPER_SHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GRID_VO grid;

        [ProtoBuf.ProtoMember(2)]
        public uint tradePasswordCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_DOWN_SHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_DOWN_SHELF
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GRID_VO grid;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_UNLOCK
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GRID_VO grid;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_BUY_SHELFTIMES
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_BUY_SHELFTIMES
    {
        [ProtoBuf.ProtoMember(1)]
        public I_GRID_VO grid;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint targetUserId;

        [ProtoBuf.ProtoMember(2)]
        public uint position;

        [ProtoBuf.ProtoMember(3)]
        public uint shelfTime;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string password = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public I_FRIEND_GRID_VO grid;

        [ProtoBuf.ProtoMember(2)]
        public uint targetUserId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_MESSAGE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_MESSAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MESSAGE_LOG> messageList = new System.Collections.Generic.List<I_MESSAGE_LOG>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRADE_HELP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRADE_HELP
    {
        [ProtoBuf.ProtoMember(1)]
        public uint position;

        [ProtoBuf.ProtoMember(2)]
        public uint helpCnt;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
