// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: trimming.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.trimming
{
    [ProtoBuf.ProtoContract]
    public class I_TRIMMING_POSITION_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public TRIMMING_POSITION position;

        [ProtoBuf.ProtoMember(2)]
        public uint itemDefId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_TRIMMING_REPLACE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_TRIMMING_REPLACE
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_TRIMMING_POSITION_VO> buildingTrimmings = new System.Collections.Generic.List<I_TRIMMING_POSITION_VO>();

    }

    [ProtoBuf.ProtoContract]
    public enum TRIMMING_POSITION
    {
        EMPTY = 0,
        WALL_LEFT = 1,
        WALL_DECORATION_LEFT = 2,
        FLOOR = 3,
        TRIMMING = 4,
        SIDE = 5,
        SOFA = 6,
        FLOWER_TABLE = 7,
        BOX = 8,
        MAT = 9,
        STAIR = 10,
        WALL_RIGHT = 11,
        COUNTER = 12,
        FLOWER_STAND = 13,
        WALL_DECORATION_RIGHT = 14,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
