// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: user.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.user
{
    [ProtoBuf.ProtoContract]
    public class I_PROFILE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint userId;

        [ProtoBuf.ProtoMember(2)]
        public uint level;

        [ProtoBuf.ProtoMember(3)]
        public uint exp;

        [ProtoBuf.ProtoMember(4)]
        public uint gold;

        [ProtoBuf.ProtoMember(5)]
        public uint diamond;

        [ProtoBuf.ProtoMember(6)]
        public uint vipTime;

        [ProtoBuf.ProtoMember(7)]
        public uint registerTime;

        [ProtoBuf.ProtoMember(8)]
        public uint lastLoginTime;

        [ProtoBuf.ProtoMember(9)]
        public uint competitionWeight;

        [ProtoBuf.ProtoMember(10)]
        public uint fighting;

        [ProtoBuf.ProtoMember(11)]
        public uint dressCharm;

        [ProtoBuf.ProtoMember(12)]
        public uint serverId;

    }

    [ProtoBuf.ProtoContract]
    public class I_PEN_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public ulong floralCharm;

        [ProtoBuf.ProtoMember(2)]
        public System.Collections.Generic.Dictionary<uint, uint> styleValue = new System.Collections.Generic.Dictionary<uint, uint>();

        [ProtoBuf.ProtoMember(3)]
        public uint penGrade;

        [ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] battlePets;

        [ProtoBuf.ProtoMember(5, IsPacked = true)]
        public uint[] battleFairys;

        [ProtoBuf.ProtoMember(6)]
        public ulong drawingPower;

    }

    [ProtoBuf.ProtoContract]
    public class I_PROFILE_INFO_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint infoType;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string info = "";

    }

    [ProtoBuf.ProtoContract]
    public class I_PROFILE_TIME_INFO_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint infoType;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string info = "";

        [ProtoBuf.ProtoMember(3)]
        public uint time;

    }

    [ProtoBuf.ProtoContract]
    public class I_BEHAVIORDAILY_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint cultivateShopCnt;

        [ProtoBuf.ProtoMember(2)]
        public uint monthCardAward;

        [ProtoBuf.ProtoMember(3)]
        public uint orderCnt;

        [ProtoBuf.ProtoMember(4)]
        [System.ComponentModel.DefaultValue("")]
        public string orderStageAward = "";

        [ProtoBuf.ProtoMember(5)]
        public uint tradePasswordCnt;

        [ProtoBuf.ProtoMember(6)]
        public uint guildDrawShareCnt;

        [ProtoBuf.ProtoMember(7)]
        public uint poltCnt;

        [ProtoBuf.ProtoMember(8)]
        public uint waterBucketCnt;

        [ProtoBuf.ProtoMember(9)]
        public uint fairyFlowerHaverCnt;

        [ProtoBuf.ProtoMember(10)]
        public uint fairyFlowerStealCnt;

    }

    [ProtoBuf.ProtoContract]
    public class I_DAILY_STAT_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint npcGiftGive;

        [ProtoBuf.ProtoMember(2)]
        public uint npcIkebanaGive;

        [ProtoBuf.ProtoMember(3)]
        public uint arenaRefreshCnt;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_UPDATE_TOWNNAME
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_UPDATE_TOWNNAME
    {
        [ProtoBuf.ProtoMember(1)]
        [System.ComponentModel.DefaultValue("")]
        public string townName = "";

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_USER_SET_AVATAR_FRAME
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_USER_SET_AVATAR_FRAME
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_USER_SET_TITLE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_USER_SET_TITLE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_UPDATE_ICON
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_UPDATE_ICON
    {
        [ProtoBuf.ProtoMember(1)]
        public uint itemId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PEN_UPGRADE
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PEN_UPGRADE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint penGrade;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_PEN_FIGHTATTR
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_PEN_FIGHTATTR
    {
        [ProtoBuf.ProtoMember(1)]
        public protobuf.fight.I_FIGHT_ATTRIBUTES_VO fightAttr;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
