// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: video.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.video
{
    [ProtoBuf.ProtoContract]
    public class I_VIDEO_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint videoId;

        [ProtoBuf.ProtoMember(2)]
        public uint wathCount;

        [ProtoBuf.ProtoMember(3)]
        public uint lastWatchTime;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
