// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: vipshop.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.misc
{
    [ProtoBuf.ProtoContract]
    public class I_MESSAGE_VIPSHOP_BUY_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public uint indexId;

        [ProtoBuf.ProtoMember(2)]
        public uint buyCount;

    }

    [ProtoBuf.ProtoContract]
    public class I_MESSAGE_SHOPSTORE_VO
    {
        [ProtoBuf.ProtoMember(1)]
        public int oddCount;

        [ProtoBuf.ProtoMember(2)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VIP_SHOP_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VIP_SHOP_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MESSAGE_VIPSHOP_BUY_VO> vipShopBuy = new System.Collections.Generic.List<I_MESSAGE_VIPSHOP_BUY_VO>();

        [ProtoBuf.ProtoMember(2)]
        public uint dailyId;

        [ProtoBuf.ProtoMember(3)]
        public uint specialId;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_VIP_SHOP_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_VIP_SHOP_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

        [ProtoBuf.ProtoMember(2)]
        public uint buyCount;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SHOPSTORE_INFO
    {
    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SHOPSTORE_INFO
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.List<I_MESSAGE_SHOPSTORE_VO> shopStore = new System.Collections.Generic.List<I_MESSAGE_SHOPSTORE_VO>();

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_SHOPSTORE_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public uint id;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_SHOPSTORE_BUY
    {
        [ProtoBuf.ProtoMember(1)]
        public I_MESSAGE_SHOPSTORE_VO store;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
