// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: welfare.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace protobuf.welfare
{
    [ProtoBuf.ProtoContract]
    public class S_MSG_WELFARE_INFO
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] waterStage;

        [ProtoBuf.ProtoMember(2)]
        [System.ComponentModel.DefaultValue("")]
        public string waterBucketSeries = "";

        [ProtoBuf.ProtoMember(3)]
        public uint waterBucketTime;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_WELFARE_WATER_STAGE
    {
        [ProtoBuf.ProtoMember(1)]
        public uint stage;

        [ProtoBuf.ProtoMember(2)]
        public bool isRetroactive;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_WELFARE_WATER_STAGE
    {
        [ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] waterStage;

    }

    [ProtoBuf.ProtoContract]
    public class C_MSG_WATER_BUCKET_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public uint pos;

        [ProtoBuf.ProtoMember(2)]
        public uint type;

    }

    [ProtoBuf.ProtoContract]
    public class S_MSG_WATER_BUCKET_AWARD
    {
        [ProtoBuf.ProtoMember(1)]
        public System.Collections.Generic.Dictionary<ulong, ulong> items = new System.Collections.Generic.Dictionary<ulong, ulong>();

        [ProtoBuf.ProtoMember(2)]
        public uint WaterBucketCnt;

        [ProtoBuf.ProtoMember(3)]
        public uint pos;

        [ProtoBuf.ProtoMember(4)]
        public bool type;

        [ProtoBuf.ProtoMember(5)]
        [System.ComponentModel.DefaultValue("")]
        public string waterBucketSeries = "";

        [ProtoBuf.ProtoMember(6)]
        public uint waterBucketTime;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
