//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_achiev_configConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 成就名字
    [ProtoMember(2)]
    public string AchievName;
    
    // 成就分类
    [ProtoMember(3)]
    public int AchievType;
    
    // 成就描述
    [ProtoMember(4)]
    public string AchievDesc;
    
    // 任务类型
    [ProtoMember(5)]
    public int TaskType;
    
    // 类型参数
    [ProtoMember(6)]
    public int TypeParam;
    
    // 所需数量
    [ProtoMember(7)]
    public int TaskNum;
    
    // 是否累积
    [ProtoMember(8)]
    public int Ishistory;
    
    // 完成奖励
    [ProtoMember(9)]
    public RewardObject[] Rewards;
    
    // 所属系列
    [ProtoMember(10)]
    public int Achievseries;
    
    // 下一个成就id
    [ProtoMember(11)]
    public int NextId;
    
    // 是否初始
    [ProtoMember(12)]
    public int IsStart;
  }
}
