//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_activity_per_infoConfig {
    
    // 活动id
    [ProtoMember(1)]
    public int Id;
    
    // 购买礼包所需消耗的道具
    [ProtoMember(2)]
    public GiftPackCostItemObject[] GiftPackCostItems;
    
    // 礼包内道具奖励
    [ProtoMember(3)]
    public GiftpackRewardObject[] GiftpackRewards;
    
    // 礼包获取的活动道具数量
    [ProtoMember(4)]
    public int GiftpackloveNum;
    
    // 礼包刷新的时间（秒）
    [ProtoMember(5)]
    public int GiftpackRefreshTime;
    
    // 礼包刷新消耗的道具
    [ProtoMember(6)]
    public int GiftPackRefreshCostItem;
    
    // 消耗多少水滴可获得1个道具
    [ProtoMember(7)]
    public int WaterNum;
    
    // 卖出多少花篮可获得1个道具
    [ProtoMember(8)]
    public int FlowerBasketNum;
    
    // 活动道具ID
    [ProtoMember(9)]
    public int CurrencyPropId;
  }
}
