//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_activity_per_exchangeConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 活动ID
    [ProtoMember(2)]
    public int ActivityId;
    
    // 0:无限购买  1:限制次数
    [ProtoMember(3)]
    public int Type;
    
    // 消耗的活动道具数量
    [ProtoMember(4)]
    public int CostItemNum;
    
    // 获得的道具
    [ProtoMember(5)]
    public GetItemObject[] GetItems;
  }
}
