//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_breedshop_levelConfig {
    
    // 等级
    [ProtoMember(1)]
    public int Level;
    
    // ft_shop_item的id 
    [ProtoMember(2)]
    public long[] ShopItemIds;
    
    // 道具的数量
    [ProtoMember(3)]
    public int[] ItemNums;
  }
}
