//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_booklist_txtConfig {
    
    // 鲜花在手册内的排列顺序
    [ProtoMember(1)]
    public int BookId;
    
    // 花的I
    //（对应物品表）
    [ProtoMember(2)]
    public int FlowerId;
    
    // 花语文本，对应zhid
    [ProtoMember(3)]
    public string FlowerLanguage;
    
    // 对应科的文本，对应zhid
    [ProtoMember(4)]
    public string FlowerFamily;
    
    // 对应属的文本，对应zhid
    [ProtoMember(5)]
    public string FlowerGenus;
    
    // 对应观赏期的文本，对应zhid
    [ProtoMember(6)]
    public string FlowerPeriod;
    
    // 对应简介的文本，对应zhid
    [ProtoMember(7)]
    public string FlowerIntroduction;
  }
}
