//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_breedshop_itemConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 价格
    [ProtoMember(2)]
    public int[] Prices;
    
    // 消耗道具id
    [ProtoMember(3)]
    public long CostItem;
    
    // 获得道具id
    [ProtoMember(4)]
    public long GetItem;
  }
}
