//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_booklistConfig {
    
    // 鲜花在手册内的排列顺序
    [ProtoMember(1)]
    public int BookId;
    
    // 花的I
    //（对应物品表）
    [ProtoMember(2)]
    public int FlowerId;
    
    // 对应
    //分享表中的id
    [ProtoMember(3)]
    public int ShareId;
    
    // 花未解锁时
    //点击弹出的tips
    [ProtoMember(4)]
    public string Tips;
    
    // 时间达到时
    //弹出的tips
    [ProtoMember(5)]
    public string ChangedTips;
    
    // 微信出处变更时间
    [ProtoMember(6)]
    public string WeixinChangeTime;
    
    // 来源配置
    [ProtoMember(7)]
    public string SourceConfig;
    
    // 缩放比例
    [ProtoMember(8)]
    public double Scale;
  }
}
