//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_buffConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int ID;
    
    // 最大叠加数量
    [ProtoMember(2)]
    public int OverLay;
    
    // buff类型
    [ProtoMember(3)]
    public int BuffType;
    
    // buff触发的概率
    [ProtoMember(4)]
    public int BuffPer;
    
    // buff图标
    [ProtoMember(5)]
    public string BuffIcon;
  }
}
