//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_clubMatch_rankConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 类型
    [ProtoMember(3)]
    public int Grade;
    
    // 名次段
    [ProtoMember(4)]
    public int[] Ranks;
    
    // 名次段奖励
    [ProtoMember(5)]
    public RewardObject[] Rewards;
  }
}
