//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_othersConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 比赛时间
    //每周3开始
    [ProtoMember(2)]
    public int MatchTime1;
    
    // 比赛时间
    //持续秒数
    [ProtoMember(3)]
    public int MatchTime2;
    
    // 马的基础速度
    //（铜，银，金，钻）
    [ProtoMember(4)]
    public string Deduction2;
    
    // 蓝点位置占比
    [ProtoMember(5)]
    public int Distance;
    
    // 放弃任务后的倒计时时间(秒)
    [ProtoMember(6)]
    public int CountDown;
    
    // 任务的刷新价格
    [ProtoMember(7)]
    public TaskRefreshObject[] TaskRefreshs;
    
    // 四种联赛任务坑总数
    [ProtoMember(8)]
    public int[] TaskNums;
    
    // 四种联赛每人可完成任务上限
    [ProtoMember(9)]
    public int[] TaskLimits;
    
    // 社团人数最小值
    //（需大于等于这个值，才能参赛）
    [ProtoMember(10)]
    public int BuddyNum;
    
    // 公会创建需要道具
    [ProtoMember(11)]
    public PersekutuanBuatObject[] PersekutuanBuats;
    
    // 公会每日捐献次数
    [ProtoMember(12)]
    public int PersekutuanjumlahDonasi;
    
    // 云游商人每日早上8点出现到次日0点
    [ProtoMember(13)]
    public int ClubKanShowTime;
    
    // 盟主超过7天不上线转让
    [ProtoMember(14)]
    public int TransLordDays;
    
    // 玩家每人每日可领取的稀有礼物存在数量上限
    [ProtoMember(15)]
    public int RareGiftNum;
    
    // 特卖鲜花的积分增加百分比
    [ProtoMember(16)]
    public int SpecialFlowerAdd;
  }
}
