//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_shopConfig {
    
    // 序号
    [ProtoMember(1)]
    public int IndexId;
    
    // 物品id
    [ProtoMember(2)]
    public ItemIdObject[] ItemIds;
    
    // 购买消耗
    [ProtoMember(3)]
    public PriceObject[] Prices;
    
    // 限购配置
    [ProtoMember(4)]
    public int[] LimitConfigs;
    
    // 花盟X级解锁
    [ProtoMember(5)]
    public int UnlockClubLv;
  }
}
