//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_plantConfig {
    
    // 花架id
    [ProtoMember(1)]
    public int Id;
    
    // 花架名字
    [ProtoMember(2)]
    public string Name;
    
    // 花盟X级解锁
    [ProtoMember(3)]
    public int UnlockClubLv;
    
    // 盟主副盟主开启消耗，为花盟资金
    [ProtoMember(4)]
    public int ClubOpenCost;
    
    // 普通开启消耗，为钻石
    [ProtoMember(5)]
    public NormalOpenCostObject[] NormalOpenCosts;
    
    // 开启后持续时间，秒数
    [ProtoMember(6)]
    public int Time;
    
    // 可种植的数量
    [ProtoMember(7)]
    public int PlantNum;
    
    // 产出间隔，秒数
    [ProtoMember(8)]
    public int PlantTime;
    
    // 额外能产出的奖励
    [ProtoMember(9)]
    public string ExtraReward;
    
    // 额外产出间隔，秒数
    [ProtoMember(10)]
    public int ExtraRewardTime;
  }
}
