//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_contract_rewardConfig {
    
    // 序号
    [ProtoMember(1)]
    public int Id;
    
    // 活动id
    [ProtoMember(2)]
    public int ActivityId;
    
    // 合约等级
    [ProtoMember(3)]
    public int ContractLevel;
    
    // 普通合约奖励
    [ProtoMember(4)]
    public CommonRewardObject[] CommonRewards;
    
    // 高级合约奖励
    [ProtoMember(5)]
    public AdvancedRewardObject[] AdvancedRewards;
    
    // 高级合约奖励
    [ProtoMember(6)]
    public SupremeRewardObject[] SupremeRewards;
  }
}
