//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_kanConfig {
    
    // 序号
    [ProtoMember(1)]
    public int Id;
    
    // 商品集合
    [ProtoMember(2)]
    public ShopItemObject[] ShopItems;
    
    // 原价，钻石数
    [ProtoMember(3)]
    public int Price;
    
    // 砍价区间，成员每次砍价的数量在此区间随机
    [ProtoMember(4)]
    public int[] Kans;
    
    // 关联的花盟等级，即花盟X级可出现
    [ProtoMember(5)]
    public int ClubLv;
    
    // 可砍价的人数
    [ProtoMember(6)]
    public int Times;
  }
}
