//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_giftdaConfig {
    
    // 大礼物等级id
    [ProtoMember(1)]
    public int Id;
    
    // 大礼物名字
    [ProtoMember(2)]
    public string Name;
    
    // 大礼物icon
    [ProtoMember(3)]
    public string Icon;
    
    // 大礼物积分
    [ProtoMember(4)]
    public int GiftPoint;
    
    // 奖励
    [ProtoMember(5)]
    public GiftRewardObject[] GiftRewards;
  }
}
