//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_giftxiaoConfig {
    
    // 小礼物等级id
    [ProtoMember(1)]
    public int Id;
    
    // 小礼物等级id
    [ProtoMember(2)]
    public int Type;
    
    // 小礼物名字
    [ProtoMember(3)]
    public string Name;
    
    // 小礼物icon
    [ProtoMember(4)]
    public string Icon;
    
    // 奖励
    [ProtoMember(5)]
    public GiftRewardObject[] GiftRewards;
    
    // 增加大礼物积分
    [ProtoMember(6)]
    public int AddPoint;
    
    // 领取人数限制
    [ProtoMember(7)]
    public int Limit;
    
    // 持续时间，秒数
    [ProtoMember(8)]
    public int Time;
    
    // 来源
    [ProtoMember(9)]
    public string Source;
  }
}
