//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_clubMatch_taskConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 1-收获指定花(低)；2-完成指定花瓶的插花；3-升级n次花；4-培育n次花；5-完成n个顾客订单；6-完成n个花市订单；7-在vip商店购买n次；8-成功抢夺花农n次；9-进行研究种植n次；10-培育商店内购买n次；11-完成鲜花订单n次；12-花台卖花n个；13-收获指定花（中）；14-收获指定花（高）
    [ProtoMember(2)]
    public int TaskType;
    
    // 任务图标
    [ProtoMember(3)]
    public string TaskIcon;
    
    // 需求物品（只抽取一个）
    [ProtoMember(4)]
    public string Taskitems;
    
    // 需求数量
    //在[A，B]AB之间随机>=,<=
    [ProtoMember(5)]
    public int[] RandomNums;
    
    // 限定时间（秒）
    //[秒数*需求数量]
    [ProtoMember(6)]
    public int LimitedTime;
    
    // 完成任务对应的分数
    //【分数*需求数量】
    [ProtoMember(7)]
    public string Score;
    
    // 出现权重
    //（在同一级联赛中）
    [ProtoMember(8)]
    public int Weights;
    
    // 任务描述
    [ProtoMember(9)]
    public string Description;
    
    // 任务品质
    [ProtoMember(10)]
    public int TaskRank;
  }
}
