//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_donasiConfig {
    
    // 公会捐献类型
    [ProtoMember(1)]
    public int Jenis;
    
    // 公会捐献消耗
    [ProtoMember(2)]
    public KonsumsiObject[] Konsumsis;
    
    // 公会捐献获得道具
    [ProtoMember(3)]
    public DapatkanObject[] Dapatkans;
    
    // 公会资金获得
    [ProtoMember(4)]
    public int Peraga;
    
    // 增加的进度值
    [ProtoMember(5)]
    public int Progress;
  }
}
