//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_shareConfig {
    
    // 序列
    [ProtoMember(1)]
    public int Id;
    
    // 第2个格子开启花费的钻石数量
    [ProtoMember(2)]
    public int Box1;
    
    // 第3个格子开启花费的钻石数量
    [ProtoMember(3)]
    public int Box2;
    
    // 第一次花费社团的资金数量
    [ProtoMember(4)]
    public int Add1;
    
    // 第二次花费社团的资金数量
    [ProtoMember(5)]
    public int Add2;
    
    // npc名字列表["npc1","npc2"]
    [ProtoMember(6)]
    public string[] Npcs;
    
    // 固定获得的社团勋章数量
    [ProtoMember(7)]
    public int RewardNum;
    
    // 额外获得的社团勋章数量
    [ProtoMember(8)]
    public int ExtraRewardNum;
  }
}
