//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_permissionConfig {
    
    // 公会职位(1会长,2副会长,3小队长,4会员)
    [ProtoMember(1)]
    public int GuildPosition;
    
    // 踢人权限
    [ProtoMember(2)]
    public int KickingPeople;
    
    // 改公告权限
    [ProtoMember(3)]
    public int Announcement;
    
    // 任命副盟主
    [ProtoMember(4)]
    public int RenFu;
    
    // 任命精英成员
    [ProtoMember(5)]
    public int RenJing;
    
    // 任命成员
    [ProtoMember(6)]
    public int RenMember;
    
    // 审批权限
    [ProtoMember(7)]
    public int Application;
    
    // 开启花房权限
    [ProtoMember(8)]
    public int FlowerHouse;
    
    // 修改图标权限
    [ProtoMember(9)]
    public int IconChange;
    
    // 修改审批条件权限
    [ProtoMember(10)]
    public int JoinCondition;
    
    // 名字
    [ProtoMember(11)]
    public string Name;
  }
}
