//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_iconConfig {
    
    // 序号
    [ProtoMember(1)]
    public int Id;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 奖励
    [ProtoMember(3)]
    public string Icon;
  }
}
