//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_club_levelConfig {
    
    // 公会等级
    [ProtoMember(1)]
    public int Level;
    
    // 升级需要道具
    [ProtoMember(2)]
    public int Peraga;
    
    // 公会人数
    [ProtoMember(3)]
    public int JumlahOrang;
    
    // 精英人数
    [ProtoMember(4)]
    public int Experience;
    
    // 副会长
    [ProtoMember(5)]
    public int VicePresident;
  }
}
