//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_contract_taskConfig {
    
    // 任务id
    [ProtoMember(1)]
    public int TaskId;
    
    // 任务类型
    [ProtoMember(2)]
    public int TaskType;
    
    // 任务类型
    [ProtoMember(3)]
    public int TypeParam;
    
    // 任务类型
    [ProtoMember(4)]
    public int Ishistory;
    
    // 随机数量区间
    [ProtoMember(5)]
    public int[] RandNums;
    
    // 任务描述
    [ProtoMember(6)]
    public string Description;
    
    // 任务所属库
    [ProtoMember(7)]
    public int Library;
    
    // 是否为每日任务 
    //1是0为挑战任务
    [ProtoMember(8)]
    public int IsDay;
    
    // 合约经验值
    [ProtoMember(9)]
    public int ContractExp;
  }
}
