//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_draw_poolConfig {
    
    // Id
    [ProtoMember(1)]
    public int Id;
    
    // 对应抽卡的活动id
    [ProtoMember(2)]
    public int EventId;
    
    // 对应道具配置
    [ProtoMember(3)]
    public PoolItemObject[] PoolItems;
    
    // 概率（配置权重）
    [ProtoMember(4)]
    public int Prob;
    
    // 品质框
    [ProtoMember(5)]
    public int Quality;
    
    // 对应第几阶段的物品
    [ProtoMember(6)]
    public int Stage;
    
    // 重复抽中转换对应的道具配置
    [ProtoMember(7)]
    public SpeciaConverObject[] SpeciaConvers;
    
    // 抽多少次之后加入奖池
    [ProtoMember(8)]
    public int DrawTime;
    
    // 是否大奖，0不是1是
    [ProtoMember(9)]
    public int IsBig;
  }
}
