//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_daily_purposeConfig {
    
    // 订单Id
    [ProtoMember(1)]
    public int PurposeId;
    
    // 宝箱字段
    [ProtoMember(2)]
    public int TreasureChest;
    
    // 目标条件(目标个数)
    [ProtoMember(3)]
    public int Goals;
    
    // 等级段
    [ProtoMember(4)]
    public int Leve;
    
    // 完成奖励[{物品ID：数量,权重}]
    [ProtoMember(5)]
    public Reward1Object[] Reward1s;
  }
}
