//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_diamond_valueConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 特惠页签的排序值，排序值小的靠前显示
    [ProtoMember(2)]
    public int Order;
    
    // 1金币2水3道具
    //6-每日礼包
    //9-每周礼包
    [ProtoMember(3)]
    public int Type;
    
    // 显示名称
    [ProtoMember(4)]
    public string Title;
    
    // icon名称，位于assets/h5icon文件夹
    [ProtoMember(5)]
    public string Icon;
    
    // 道具，数量
    //可填多个值
    [ProtoMember(6)]
    public ItemObject[] Items;
    
    // 原价
    [ProtoMember(7)]
    public int OriginalPrice;
    
    // 价格,钻石
    [ProtoMember(8)]
    public int Price;
    
    // 限购
    [ProtoMember(9)]
    public int[] LimitConfigs;
    
    // 是否首次购买半价
    [ProtoMember(10)]
    public int IsFirstHalf;
  }
}
