//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_draw_configConfig {
    
    // Id
    [ProtoMember(1)]
    public int Id;
    
    // 抽一次消耗的道具
    [ProtoMember(2)]
    public DrawItemObject[] DrawItems;
    
    // 抽一次额外获得的道具
    [ProtoMember(3)]
    public ScoreItemObject[] ScoreItems;
    
    // 必得次数配置，必得是大奖的道具
    [ProtoMember(4)]
    public int MustGetTime;
    
    // 是否多阶段抽卡，0不是，多阶段填写具体有几阶段
    [ProtoMember(5)]
    public int IsStage;
    
    // 是否多阶段抽卡，0不是，多阶段填写具体有几阶段
    [ProtoMember(6)]
    public int[] StageItems;
  }
}
