//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_diamond_gift_packConfig {
    
    // 礼包ID
    [ProtoMember(1)]
    public int GiftPackageId;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 触发等级
    [ProtoMember(3)]
    public int Level;
    
    // 微信触发时间
    [ProtoMember(4)]
    public string WeixinTriggerTime;
    
    // 微信结束时间
    [ProtoMember(5)]
    public string WeixinEndTime;
    
    // 存在时间（秒）
    [ProtoMember(6)]
    public int TimeOfExistence;
    
    // 道具内容
    [ProtoMember(7)]
    public RewardPropsObject[] RewardPropss;
    
    // 填写：非道具的奖励物
    //
    //用;来区别不同奖励物类型。
    [ProtoMember(8)]
    public string SpecialId;
    
    // 购买价格
    [ProtoMember(9)]
    public int Price;
    
    // 礼包名字（图片）
    [ProtoMember(10)]
    public string UiEntrance;
    
    // UI内容
    [ProtoMember(11)]
    public string UiContent;
    
    // 原价
    [ProtoMember(12)]
    public string OriginalPrice;
    
    // 礼包名字
    [ProtoMember(13)]
    public string Name;
  }
}
