//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_days_loginConfig {
    
    // 序列id
    [ProtoMember(1)]
    public int IndexId;
    
    // 天数
    [ProtoMember(2)]
    public AwardObject[] Awards;
    
    // 展示icon
    [ProtoMember(3)]
    public string Icon;
  }
}
