//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_emojiConfig {
    
    // text id
    [ProtoMember(1)]
    public int Id;
    
    // icon文件名
    [ProtoMember(2)]
    public string Icon;
    
    // 表情包名字
    [ProtoMember(3)]
    public string Name;
  }
}
