//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_event_exchangeConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 对应抽卡的活动id
    [ProtoMember(2)]
    public int EventId;
    
    // 对应兑换物道具配置
    [ProtoMember(3)]
    public RewardObject[] Rewards;
    
    // 对应消耗配置
    [ProtoMember(4)]
    public ExpendObject[] Expends;
    
    // 限购次数（0表示不限购）
    [ProtoMember(5)]
    public int[] LimitConfigs;
    
    // 品质框
    [ProtoMember(6)]
    public int Quality;
    
    // 阶段
    [ProtoMember(7)]
    public int Stage;
  }
}
