//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_enemy_configConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 名字
    [ProtoMember(2)]
    public string Name;
    
    // 简介
    [ProtoMember(3)]
    public string Desc;
    
    // 敌人类型
    [ProtoMember(4)]
    public int EnemyType;
    
    // 动画名字
    [ProtoMember(5)]
    public string SpineName;
    
    // 攻击类型
    [ProtoMember(6)]
    public int AttackType;
    
    // 属性id
    [ProtoMember(7)]
    public int AttId;
    
    // 技能id
    [ProtoMember(8)]
    public long CommonSkillID;
  }
}
