//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_enemy_attConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 攻击
    [ProtoMember(2)]
    public int Attack;
    
    // 生命
    [ProtoMember(3)]
    public int Hp;
    
    // 防御
    [ProtoMember(4)]
    public int Def;
    
    // 暴击
    [ProtoMember(5)]
    public double Crit;
    
    // 闪避
    [ProtoMember(6)]
    public double Dodge;
    
    // 击晕
    [ProtoMember(7)]
    public double Stun;
    
    // 吸血
    [ProtoMember(8)]
    public double LifeSteal;
    
    // 反弹
    [ProtoMember(9)]
    public double Counter;
    
    // 追击
    [ProtoMember(10)]
    public double Combo;
    
    // 抗暴击
    [ProtoMember(11)]
    public double AntiCrit;
    
    // 抗击晕
    [ProtoMember(12)]
    public double AntiStun;
    
    // 抗吸血
    [ProtoMember(13)]
    public double AntiLifeSteal;
    
    // 抗反弹
    [ProtoMember(14)]
    public double AntiCounter;
    
    // 命中
    [ProtoMember(15)]
    public double AntiDodge;
    
    // 强化宠物
    [ProtoMember(16)]
    public double PetUp;
    
    // 弱化宠物
    [ProtoMember(17)]
    public double PetDown;
    
    // 强化治疗
    [ProtoMember(18)]
    public double CureUp;
    
    // 弱化治疗
    [ProtoMember(19)]
    public double CureDown;
    
    // 最终增伤
    [ProtoMember(20)]
    public double FinalUp;
    
    // 最终减伤
    [ProtoMember(21)]
    public double FinalDown;
    
    // 无视战斗属性
    [ProtoMember(22)]
    public double IgnoreAttributes;
    
    // 无视战斗抗性
    [ProtoMember(23)]
    public double IgnoreResistance;
  }
}
