//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_flower_star_refreshConfig {
    
    // 刷新星级
    [ProtoMember(1)]
    public int RefreshStar;
    
    // 消耗的培育道具百分比
    [ProtoMember(2)]
    public int PropPercent;
    
    // 鲜花升到第X级消耗的金币
    [ProtoMember(3)]
    public int FlowerLevel;
    
    // 消耗的百分比
    [ProtoMember(4)]
    public int ConsumePercent;
    
    // 消耗货币类型
    [ProtoMember(5)]
    public int CurrencyType;
  }
}
