//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_flower_star_additionConfig {
    
    // 序列
    [ProtoMember(1)]
    public int ID;
    
    // 加成类型
    [ProtoMember(2)]
    public int AdditionKind;
    
    // 数值类型
    [ProtoMember(3)]
    public int NumKind;
    
    // 加成百分比
    [ProtoMember(4)]
    public int AdditionPercent;
    
    // 加成数值
    [ProtoMember(5)]
    public int AdditionNum;
    
    // 权重
    [ProtoMember(6)]
    public int Weight;
  }
}
