//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_flowerarketConfig {
    
    // 编号
    [ProtoMember(1)]
    public int Id;
    
    // 槽位(读取语言表)
    [ProtoMember(2)]
    public int[] Levels;
    
    // 数量
    [ProtoMember(3)]
    public int Quantity;
  }
}
