//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_friends_deal_itemsConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 道具id
    [ProtoMember(2)]
    public int ItemId;
    
    // 【单价最小值，推荐值，最大值】
    //货币类型为：金币！！！
    [ProtoMember(3)]
    public int[] UnitPrices;
    
    // 【数量最小值，最大值】
    [ProtoMember(4)]
    public int[] ItemAmounts;
    
    // 排序id
    [ProtoMember(5)]
    public int BookId;
  }
}
