//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_boxConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 普通盲盒集合
    [ProtoMember(2)]
    public int[] NormalBoxs;
    
    // 隐藏盲盒
    [ProtoMember(3)]
    public int HideBox;
    
    // 隐藏概率
    [ProtoMember(4)]
    public int HideProb;
    
    // 抽卡消耗
    [ProtoMember(5)]
    public SingleCostObject[] SingleCosts;
  }
}
