//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_relationConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 羁绊名字，zhid
    [ProtoMember(2)]
    public string RelationName;
    
    // 花仙id集合
    [ProtoMember(3)]
    public int[] FairyCombinations;
    
    // 花仙每2级提升
    //1级羁绊等级
    [ProtoMember(4)]
    public int FairyLevelUp;
    
    // 基础属性加成
    [ProtoMember(5)]
    public string RelationAtts;
    
    // 羁绊等级每升1级增加的属性，千分比
    [ProtoMember(6)]
    public int LevelAtts;
  }
}
