//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_florist_suitConfig {
    
    // 主键，等级
    [ProtoMember(1)]
    public int Id;
    
    // 家具套装名字
    [ProtoMember(2)]
    public string Name;
    
    // 家具图标图片名字
    [ProtoMember(3)]
    public string Icon;
    
    // 绘力要求
    [ProtoMember(4)]
    public int[] Furnitures;
    
    // 品质
    [ProtoMember(5)]
    public int Quality;
    
    // 收集数量
    [ProtoMember(6)]
    public int[] RequireNums;
    
    // 等级奖励
    [ProtoMember(7)]
    public string AttrsAdd;
    
    // 是否默认套装
    [ProtoMember(8)]
    public int IsDefault;
    
    // 对应的花店扩张等级
    [ProtoMember(9)]
    public int ExpandLv;
  }
}
