//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_friends_deal_gridConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 0-免费；1-道具消耗 2累积金币
    [ProtoMember(2)]
    public int Type;
    
    // 解锁格子的消耗
    [ProtoMember(3)]
    public UnlockConsumeObject[] UnlockConsumes;
    
    // 累积金币
    [ProtoMember(4)]
    public int GoldUnlock;
    
    // 货架每日可上架次数
    [ProtoMember(5)]
    public int PutawayTimes;
    
    // 每次购买价格
    //货币类型为：钻石！
    [ProtoMember(6)]
    public int[] DiamondConsumes;
  }
}
