//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_luckyConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 当前轮次幸运值数
    [ProtoMember(2)]
    public int LuckyNum;
    
    // 达到幸运值下一轮必出的品质id
    [ProtoMember(3)]
    public int LuckyQuality;
  }
}
