//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_doubleConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 翻倍星光花id组合
    [ProtoMember(2)]
    public int[] FairyrIds;
    
    // 开始时间配置
    [ProtoMember(3)]
    public string TimeConfig1;
    
    // 结束时间配置
    [ProtoMember(4)]
    public string TimeConfig2;
  }
}
