//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_figureConfig {
    
    // 藏品id
    [ProtoMember(1)]
    public int Id;
    
    // 主花id
    [ProtoMember(2)]
    public int MainFlowerId;
    
    // 副花id
    [ProtoMember(3)]
    public int ViceFlowerId;
    
    // 花仙id
    [ProtoMember(4)]
    public int FairyId;
    
    // 经验的道具id
    [ProtoMember(5)]
    public int ExpId;
    
    // 额外概率
    [ProtoMember(6)]
    public int[] WeightLevels;
    
    // 消耗的经验道具
    [ProtoMember(7)]
    public int[] CostLevelExps;
    
    // 消耗的金币道具
    [ProtoMember(8)]
    public int[] CostLevelCoins;
    
    // 收获花仙+经验
    [ProtoMember(9)]
    public int FairyAddExp;
    
    // 重复抽中转化经验
    [ProtoMember(10)]
    public int DrawConvertExp;
    
    // 升至顶级时，重复抽中对应转化为金币
    [ProtoMember(11)]
    public int TopConvertExp;
  }
}
