//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_florist_levelConfig {
    
    // 主键，等级
    [ProtoMember(1)]
    public int Id;
    
    // 绘力要求
    [ProtoMember(2)]
    public int PowerNum;
    
    // 绘力奖励
    [ProtoMember(3)]
    public PowerRewardObject[] PowerRewards;
    
    // 等级要求
    [ProtoMember(4)]
    public int LvNum;
    
    // 等级奖励
    [ProtoMember(5)]
    public LvRewardObject[] LvRewards;
    
    // 培育花要求
    [ProtoMember(6)]
    public int FlowerNum;
    
    // 培育花奖励
    [ProtoMember(7)]
    public FlowerRewardObject[] FlowerRewards;
    
    // 花瓶要求
    [ProtoMember(8)]
    public int VaseNum;
    
    // 花瓶奖励
    [ProtoMember(9)]
    public VaseRewardObject[] VaseRewards;
    
    // 服装要求
    [ProtoMember(10)]
    public int ClothesNum;
    
    // 服装奖励
    [ProtoMember(11)]
    public ClothesRewardObject[] ClothesRewards;
    
    // 鲜花等级上限
    [ProtoMember(12)]
    public int FlowerLimit;
    
    // 摆台数量上限
    [ProtoMember(13)]
    public int SellLimit;
    
    // 升级奖励
    [ProtoMember(14)]
    public UpRewardObject[] UpRewards;
    
    // 扩张等级
    [ProtoMember(15)]
    public int ExpandLv;
  }
}
