//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_levelConfig {
    
    // 等级
    [ProtoMember(1)]
    public string Id;
    
    // 花仙id，主键1
    [ProtoMember(2)]
    public int FairyId;
    
    // 等级，主键2
    [ProtoMember(3)]
    public int Level;
    
    // 属性加成
    //叠加
    [ProtoMember(4)]
    public string LevelAtts;
    
    // 所带技能id
    [ProtoMember(5)]
    public long SkillId;
    
    // 是否升级技能
    [ProtoMember(6)]
    public int IsSkillUp;
    
    // 升级所需花仙碎片数量
    [ProtoMember(7)]
    public int CostNum;
    
    // 喜好鲜花订单金币提升百分比
    [ProtoMember(8)]
    public double FavorGoldUp;
    
    // 喜好鲜花风格值提升百分比
    [ProtoMember(9)]
    public double FavorStyleUp;
  }
}
