//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_configConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 名字
    [ProtoMember(2)]
    public string Name;
    
    // 简介
    [ProtoMember(3)]
    public string Desc;
    
    // 品质
    [ProtoMember(4)]
    public int Quality;
    
    // 对应碎片id
    [ProtoMember(5)]
    public int ShardId;
    
    // 合成所需要
    //碎片数量
    [ProtoMember(6)]
    public int ComposeNum;
    
    // 召唤花仙时的权重
    [ProtoMember(7)]
    public int SummonProb;
    
    // 召唤花仙时1,2,3倍率下的碎片数量
    [ProtoMember(8)]
    public int[] SummonNums;
    
    // 喜爱的鲜花花朵id集合
    [ProtoMember(9)]
    public int[] FavorFlowers;
  }
}
