//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fairy_identifyConfig {
    
    // 品质id
    [ProtoMember(1)]
    public int Id;
    
    // 鉴定所需时间秒
    [ProtoMember(2)]
    public int Times;
    
    // 鉴定可获得
    [ProtoMember(3)]
    public IdentifyRewardObject[] IdentifyRewards;
  }
}
