//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_fundConfig {
    
    // 序号
    [ProtoMember(1)]
    public int Id;
    
    // 基金id
    [ProtoMember(2)]
    public int FundType;
    
    // 领奖等级
    [ProtoMember(3)]
    public int ReceiveLv;
    
    // 每级发放的奖励内容
    [ProtoMember(4)]
    public ItemRewardObject[] ItemRewards;
  }
}
