//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_florist_furnitureConfig {
    
    // 主键，等级
    [ProtoMember(1)]
    public int Id;
    
    // 打造所需消耗的材料
    [ProtoMember(2)]
    public CreateCostObject[] CreateCosts;
    
    // 家具类型
    [ProtoMember(3)]
    public int Type;
    
    // 品质
    [ProtoMember(4)]
    public int Quality;
    
    // 品质
    [ProtoMember(5)]
    public int Prosperity;
  }
}
