//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_game_payConfig {
    
    // 产品id
    [ProtoMember(1)]
    public string ProductId;
    
    // 1.钻石 2.金币
    [ProtoMember(2)]
    public int Type;
    
    // 语言文字
    [ProtoMember(3)]
    public string Name;
    
    // 数量
    [ProtoMember(4)]
    public int Count;
    
    // 价格$
    [ProtoMember(5)]
    public float Price;
    
    // 是否推荐
    [ProtoMember(6)]
    public bool IsRecommended;
    
    // 显示顺序
    [ProtoMember(7)]
    public int Order;
    
    // 美术资源
    [ProtoMember(8)]
    public string Resource;
    
    // 3倍四选一
    [ProtoMember(9)]
    public int IsThree;
    
    // 首充额外赠送数量
    [ProtoMember(10)]
    public int FirstExtraGive;
  }
}
