//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_game_eventConfig {
    
    // 活动id
    [ProtoMember(1)]
    public int IndexId;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 弹窗规则：
    //1-不弹窗
    //2-每日首登弹窗
    //3-每次登陆都弹窗
    [ProtoMember(3)]
    public int PopWindow;
    
    // 微信活动开启时间
    [ProtoMember(4)]
    public string WeixinTriggerTime;
    
    // 微信活动结束时间
    [ProtoMember(5)]
    public string WeixinEndTime;
    
    // 活动名称
    //文字都是title_前缀
    //图片都是png_前缀
    [ProtoMember(6)]
    public string Name;
    
    // 活动描述，显示在活动界面上的活动描述
    //文字都是text_前缀
    //图片都是png_前缀
    [ProtoMember(7)]
    public string Description;
    
    // 数据参数
    [ProtoMember(8)]
    public string Parms;
    
    // 关联
    //功能解锁配置|ft_game_system_unlock
    [ProtoMember(9)]
    public int FunctionId;
  }
}
