//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_game_banedtextConfig {
    
    // 序号,必须是顺序的
    [ProtoMember(1)]
    public int Index;
    
    // 文本内容
    [ProtoMember(2)]
    public string BanedList;
  }
}
