//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_ground_lineConfig {
    
    // 线路id
    [ProtoMember(1)]
    public int LineId;
    
    // 导航点x坐标
    [ProtoMember(2)]
    public float[] Coordinate_xs;
    
    // 导航点y坐标
    [ProtoMember(3)]
    public float[] Coordinate_ys;
    
    // 导航点停留时间
    [ProtoMember(4)]
    public int[] Times;
  }
}
