//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_game_system_unlockConfig {
    
    // 功能id
    [ProtoMember(1)]
    public int SysId;
    
    // 是否任务解锁
    [ProtoMember(2)]
    public int IsTaskUnlock;
    
    // 解锁等级
    [ProtoMember(3)]
    public int Level;
    
    // 功能id
    [ProtoMember(4)]
    public string SysIcon;
  }
}
