//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_gift_pack2Config {
    
    // id
    [ProtoMember(1)]
    public int GiftId;
    
    // 类型1：随机后，物品剔除
    //类型2：随机后，物品不剔除，继续参与随机
    [ProtoMember(2)]
    public int Type;
    
    // 礼包内的参与随机掉落的物品id及数量及权重
    [ProtoMember(3)]
    public string RandomDropItems;
    
    // 随机次数
    [ProtoMember(4)]
    public int RandomTimes;
    
    // 礼包内的必定掉落物品id及数量
    [ProtoMember(5)]
    public MustDropItemsObject[] MustDropItemss;
    
    // 兑换该礼包所需消耗的物品
    [ProtoMember(6)]
    public PayOutObject[] PayOuts;
  }
}
