//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_gameConfig {
    
    // 索引号,数据不可变
    [ProtoMember(1)]
    public string IndexId;
    
    // 游戏初始化时开放的地块id，填写格式为：[区块号1,区块号2，...]
    [ProtoMember(2)]
    public int[] InitGroundBlockIdss;
    
    // 游戏初始化赠送的道具 eg： {"entityId": count, }
    [ProtoMember(3)]
    public InitItemObject[] InitItems;
    
    // 左侧墙壁左顶点的坐标，格式为：左端X坐标,左端Y坐标
    [ProtoMember(4)]
    public int[] WallLefts;
    
    // 右侧侧墙壁下端顶点的坐标，格式为：下端X坐标,下端Y坐标
    [ProtoMember(5)]
    public int[] WallRights;
    
    // 中间的墙壁坐标，格式为：X坐标,Y坐标
    [ProtoMember(6)]
    public int[] WallMiddles;
    
    // 门，int为向下取整，调整为固定位置
    //门的X坐标=int((中间墙的X坐标-1-左侧墙左顶点)/2)+左侧墙左顶点+1；
    //暂时调整：门的X坐标=中间墙的X坐标-2；
    //门的占格数=int(墙的长度/门系数）；填充方式先左一格，再右一格;
    //暂时调整：门的占格数=CEILING.MATH(墙的长度/门系数,1）；填充方式先左一格，再右一格
    [ProtoMember(7)]
    public float DoorParameter;
    
    // 普通订单板系统的初始订单，普通订单板初始订单读取此值，之后按照正常的随机生成流程刷新，填写格式为：对应普通订单板系统槽位为1的初始订单id,对应普通订单板系统槽位为2的初始订单id,对应普通订单板系统槽位为3的初始订单id（暂时只填写到3个，对应普通订单板初始解锁3个订单槽位的设定）
    [ProtoMember(8)]
    public int[] PrimaryOrders;
    
    // 豪华列车的刷新时间点，填写格式：刷新时刻对应的秒数（此数值为从每日的0点整点到具体时刻经过的秒数）；eg：3600，表示刷新时刻为每日的凌晨1点整，此数值为一天内的具体时刻，所以数值必须为小于等于86400的数值
    [ProtoMember(9)]
    public int LuxTrainResetTime;
    
    // 每日可点赞数
    [ProtoMember(10)]
    public int DailyLikeLimit;
    
    // 点赞次数的重置时间点，填写格式：刷新时刻对应的秒数（此数值为从每日的0点整点到具体时刻经过的秒数）；eg：3600，表示刷新时刻为每日的凌晨1点整，此数值为一天内的具体时刻，所以数值必须为小于等于86400的数值
    [ProtoMember(11)]
    public int DailyLikeResetTime;
    
    // 游戏初始化赠送的货币 eg： {"entityId": count, }
    [ProtoMember(12)]
    public InitMoneyObject[] InitMoneys;
    
    // 初始头像id
    [ProtoMember(13)]
    public int InitIcon;
    
    // 初始国籍
    [ProtoMember(14)]
    public int InitCountry;
    
    // 玩家名字utf-8字节长度
    [ProtoMember(15)]
    public int PlayerNameBit;
    
    // 好友上限
    [ProtoMember(16)]
    public int FriendsLimit;
    
    // 关注上限
    [ProtoMember(17)]
    public int FollowingLimit;
    
    // 粉丝上限
    [ProtoMember(18)]
    public int FansLimit;
    
    // 默认商会国籍，对应为商会国籍配置表的index值
    [ProtoMember(19)]
    public int InitcocCountry;
    
    // 默认商会logo，对应为商会logo配置表的index值
    [ProtoMember(20)]
    public int InitcocLogo;
    
    // 默认商会加人方式
    //1.任何人都能加入的模式，只要玩家达到等级需求，直接就能加入；
    //2.请求加入的方式，玩家点申请之后需要商会管理员同意方能加入；
    //3.邀请加入的方式，玩家不可主动加入商会，只能由商会的管理要求加入；
    [ProtoMember(21)]
    public int CocJoinType;
    
    // 默认加入商会所需的玩家等级，一般填1，后期由玩家自己调整
    [ProtoMember(22)]
    public int CocJoinLv;
    
    // 默认创建商会金币
    [ProtoMember(23)]
    public int CocCreateGold;
    
    // 商会自动更换会长所需时间，单位s
    [ProtoMember(24)]
    public int CocPresidentAssignmentTime;
    
    // 商会初始活跃度计数时间戳
    [ProtoMember(25)]
    public int InitCocActivityTime;
    
    // 默认活跃度重置步长
    [ProtoMember(26)]
    public int InitCocActivityIntervalValue;
    
    // 商会名称utf-8字节长度
    [ProtoMember(27)]
    public int CocNameBit;
    
    // 宝石，金币比率，换算公式：金币数=宝石数*比率
    [ProtoMember(28)]
    public int GemGoldRatio;
    
    // 进入游戏的默认屏幕中心坐标
    [ProtoMember(29)]
    public int[] ScreenCenters;
    
    // 玩家可拖拽网格区域左下角
    [ProtoMember(30)]
    public float[] ScreenLeftLowers;
    
    // 玩家可拖拽网格区域右上角
    [ProtoMember(31)]
    public float[] ScreenRightUppers;
    
    // npc生成间隔时间;格式：[最小值，最大值]
    [ProtoMember(32)]
    public int[] NpcCreateTimes;
    
    // npc数量；格式：[最小值，最大值]
    [ProtoMember(33)]
    public int[] NpcCounts;
    
    // 收银台出现气泡提示的储存金币下限
    [ProtoMember(34)]
    public int CashRegisterHintLimit;
    
    // 每日可完成功能建筑订单上限,格式：{"功能建筑订单槽位号":上限数量,……}
    [ProtoMember(35)]
    public SpecialOrderDailyLimitObject[] SpecialOrderDailyLimits;
    
    // 功能建筑次数购买花费；
    //eg：{"1":1,"4":3，"6":5} 
    //表示：
    //1<=次数<4时，花费为1宝石，
    //4<=次数<6时，花费为3宝石，
    //次数>=6时，花费为5宝石
    [ProtoMember(36)]
    public SpecialOrderDailyResetPriceObject[] SpecialOrderDailyResetPrices;
    
    // 全局掉落随机次数区间；
    //格式：[区间1长度，区间2长度,….],
    //a）区间的个数表示玩家每天可以拥有的全局掉落总次数；
    //b）第n次全局掉落发生所需的行为次数=random（1，区间n长度）
    //c）当玩家达到所需的行为次数时，必定给予一次全局掉落奖励
    [ProtoMember(37)]
    public int[] ExtraDropValueIntervals;
    
    // 同时可索取的数量,暂不使用
    [ProtoMember(38)]
    public int DonationListLimit;
    
    // 索取行为单个物品可索取数上限
    [ProtoMember(39)]
    public int DonationAskLimit;
    
    // 索取行为单条索取列表可捐赠数上限,暂不使用
    [ProtoMember(40)]
    public int DonationGiveLimit;
    
    // 索取信息持续时间
    [ProtoMember(41)]
    public int DonationStayTime;
    
    // 索取cd
    [ProtoMember(42)]
    public int DonationCd;
    
    // 留言板玩家输入文本长度，utf-8字节长度
    [ProtoMember(43)]
    public int MessageBit;
    
    // 商会频道保留留言数
    [ProtoMember(44)]
    public int MessageCoc;
    
    // 商会频道两次聊天时间间隔
    [ProtoMember(45)]
    public int MessageCocInterval;
    
    // 世界频道保留留言数
    [ProtoMember(46)]
    public int MessageWorld;
    
    // 世界频道两次聊天时间间隔
    [ProtoMember(47)]
    public int MessageWorldInterval;
    
    // 每日可帮助复活乔木灌木次数
    [ProtoMember(48)]
    public int HelpTimeDailyLimit;
    
    // 每次帮助获得的奖励
    [ProtoMember(49)]
    public HelpRewardObject[] HelpRewards;
    
    // 邮件标题文本长度，utf-8字节长度
    [ProtoMember(50)]
    public int MailTitleBit;
    
    // 邮件文本长度，utf-8字节长度，界面可以显示224个左右的英文字符，后端能支持到256个字节，暂时填224，若有超长邮件需要后端改数据库。
    [ProtoMember(51)]
    public int MailBit;
    
    // 商会订单活动预告开启周别（周1为1，周日为7,以此类推）
    [ProtoMember(52)]
    public int CocOrderStart;
    
    // 商会订单活动预告开启时间（当日的0点到开启时刻的秒数）此数值暂未使用
    [ProtoMember(53)]
    public int CocOrderStartTime;
    
    // 商会订单活动预告持续时间，该时间结束时间点为订单活动开启时间。
    [ProtoMember(54)]
    public int CocOrderAdvanceTime;
    
    // 商会订单活动持续时间，该时间结束时间点为订单活动领奖开启时间。
    [ProtoMember(55)]
    public int CocOrderEventTime;
    
    // 商会领奖持续时间，该时间结束时间点为下次订单活动预告开启时间。
    [ProtoMember(56)]
    public int CocOrderBonusTime;
    
    // 商会日常任务重置花费
    [ProtoMember(57)]
    public int CocDailyTaskResetCost;
    
    // 商会同时可以领取的日常任务数
    [ProtoMember(58)]
    public int CocDailyTaskReceiveLimit;
    
    // 新手期等级。
    //1. 等级<=X时，算新手引导 加速收0钻；X暂定为3
    //2.适用加速不收钱的花的ID：薰衣草，金盏菊；
    //3.适用加速不收钱的机器的ID：干花机，蜂巢；
    //4.适用加速不收钱的产品的ID：干熏衣草；
    //
    [ProtoMember(59)]
    public int NewPlayerLv;
    
    // 可免费加速的最终引导步骤。填写格式{"引导任务编组号":子步骤号}即对应引导配置表的两个字段{"guideGroup":step}，（因在新手期是否可以使用免费加速前后端的判断存在差异，填写此值辅助newPlayerLv使用，以解决因玩家未按照正常的新手引导流程游戏而在获得免费加速效果且不消耗的情况下升级超过newPlayerLv配置值时产生的报错。），2018年3月7日版本未使用。
    [ProtoMember(60)]
    public NewPlayerGuideIdObject[] NewPlayerGuideIds;
    
    // 新手期加速价格为0的花，2018年3月7日版本未使用。
    [ProtoMember(61)]
    public int[] NewPlayerLvFlowerIds;
    
    // 新手期加速价格为0的产品，2018年3月7日版本未使用。
    [ProtoMember(62)]
    public int[] NewPlayerLvProduceIds;
    
    // 新手期加速建造价格为0的建筑，2018年3月7日版本未使用。
    [ProtoMember(63)]
    public int[] NewPlayerLvBuildingIds;
    
    // 生产队列上限值，适用于生产工具，花艺台.每个机器的堆叠上限不应该超过60，（此数值*机器槽位上限<=60）
    [ProtoMember(64)]
    public int ProduceQueueLimit;
    
    // 初始的一些订单，为方便玩家度过新手期的订单配置
    [ProtoMember(65)]
    public int[] FirstOrders;
    
    // 初始的一些订单，为方便玩家度过新手期的火车订单配置
    [ProtoMember(66)]
    public int[] FirstTrainOrders;
    
    // 初始的一些订单，为方便玩家度过新手期的豪华火车订单配置
    [ProtoMember(67)]
    public int[] FirstLuxuryTrainOrders;
    
    // H5玩家点击下载手游端并登录的奖励
    [ProtoMember(68)]
    public GiftForWebPlayersObject[] GiftForWebPlayerss;
    
    // H5玩家点击下载手游端并登录的奖励发放邮件描述
    [ProtoMember(69)]
    public string MailForWebGift;
    
    // 订单删除按钮解锁等级,当玩家<=此等级时，玩家不可删除订单。
    [ProtoMember(70)]
    public int OrderTearUnlockLv;
    
    // 新手期NPC订单提醒等级，当玩家<=此等级时，NPC会按照时间去提醒玩家做订单。
    [ProtoMember(71)]
    public int OrderNoviceLv;
    
    // 新手期NPC订单提醒时间间隔
    [ProtoMember(72)]
    public int OrderRemindInterval;
    
    // party活动坐标
    [ProtoMember(73)]
    public int[] PartyPositions;
    
    // party活动占地
    [ProtoMember(74)]
    public int[] PartySizes;
  }
}
