//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_gift_packConfig {
    
    // id
    [ProtoMember(1)]
    public int GiftId;
    
    // 物品权重
    [ProtoMember(2)]
    public ItemsObject[] Itemss;
  }
}
