//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_game_guideConfig {
    
    // 引导步骤
    [ProtoMember(1)]
    public int IndexId;
    
    // 引导被打断重新开始步骤
    [ProtoMember(2)]
    public int GuideGroup;
    
    // 引导类型  0：正常显示不加指引性的引导，1：npc全屏对话框 配置npc对话，2：npc非全屏对话框+手指引导 配置对话内容和指引对象，3：场景物引导 需配置场景物id，4：界面UI引导 需配置界面ui控制名字，5：显示引导视频 需配置引导视频
    [ProtoMember(3)]
    public int GuideType;
    
    // 执行下一步骤的IndexId，0表示引导结束
    [ProtoMember(4)]
    public int SkipStep;
    
    // 引导剧情文本
    [ProtoMember(5)]
    public string GuideStr;
    
    // 引导剧情显示的人物动画
    [ProtoMember(6)]
    public int NpcSpineType;
    
    // 场景建筑Id,配置为1时是土地的第一个或桌子的第一个，代码中作特殊处理
    [ProtoMember(7)]
    public int StructureId;
    
    // 下一步延迟执行时间
    [ProtoMember(8)]
    public float Delay;
    
    // 需要引导的页面
    [ProtoMember(9)]
    public string OpenView;
    
    // 引导的目标路径
    [ProtoMember(10)]
    public string TargetPath;
    
    // 页面类型全屏和弹窗
    [ProtoMember(11)]
    public int PanelType;
    
    // 操作说明种植图片
    [ProtoMember(12)]
    public string GuideImage;
    
    // 需要特殊处理的引导目标
    [ProtoMember(13)]
    public string GuideObject;
    
    // 微调引导的x方向位置
    [ProtoMember(14)]
    public float GuideOffsetX;
    
    // 微调引导的y方向位置
    [ProtoMember(15)]
    public float GuideOffsetY;
    
    // 引导列表目标的下标
    [ProtoMember(16)]
    public int Index;
  }
}
