//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_hua_breakConfig {
    
    // 双主键id
    [ProtoMember(1)]
    public string ID;
    
    // 品质id
    [ProtoMember(2)]
    public int QualityId;
    
    // 突破等级
    [ProtoMember(3)]
    public int BreakLv;
    
    // 突破消耗
    [ProtoMember(4)]
    public BreakCostObject[] BreakCosts;
  }
}
