//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_hua_levelConfig {
    
    // 双主键id
    [ProtoMember(1)]
    public string ID;
    
    // 模版id
    [ProtoMember(2)]
    public int MouldId;
    
    // 鲜花等级
    [ProtoMember(3)]
    public int Level;
    
    // 每次收获的作物数量
    [ProtoMember(4)]
    public int CropCount;
    
    // 种子消耗
    [ProtoMember(5)]
    public int SeedCost;
    
    // 金币消耗
    [ProtoMember(6)]
    public int GoldCost;
    
    // 采摘间隔
    //(秒为单位)
    [ProtoMember(7)]
    public int Interval;
    
    // 采摘次数
    [ProtoMember(8)]
    public int Frequency;
    
    // 每次收获的时候给的经验
    [ProtoMember(9)]
    public int Experience;
    
    // 花朵保底数量
    [ProtoMember(10)]
    public int Baodi;
    
    // 种子掉落数量
    [ProtoMember(11)]
    public int SeedProp;
    
    // 种子掉落权重
    [ProtoMember(12)]
    public int SeedWeight;
    
    // 升级增加的繁荣度
    [ProtoMember(13)]
    public int Prosperity;
  }
}
