//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_hua_gradeConfig {
    
    // 双主键id
    [ProtoMember(1)]
    public string ID;
    
    // 对应品质
    [ProtoMember(2)]
    public int QualityId;
    
    // 品阶等级
    [ProtoMember(3)]
    public int GradeLv;
    
    // 升品阶的消耗,消耗自身碎片
    [ProtoMember(4)]
    public int GradeCost1;
    
    // 升品阶的消耗,消耗通用碎片
    [ProtoMember(5)]
    public int GradeCost2;
    
    // 升品阶提升的属性和属性值
    [ProtoMember(6)]
    public string GradeAttribute;
    
    // 进阶值，计算芳华值用，不展示
    [ProtoMember(7)]
    public int GradeValue;
    
    // 进阶增加的风格值
    [ProtoMember(8)]
    public int StyleValue;
  }
}
