//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_hua_breedConfig {
    
    // 花朵id
    [ProtoMember(1)]
    public int FlowerId;
    
    // 需求的对应花卡id
    [ProtoMember(2)]
    public int TaskId;
    
    // 培育需消耗的道具id 数量
    [ProtoMember(3)]
    public ItemIdObject[] ItemIds;
    
    // 培育花的等待时间(秒)
    [ProtoMember(4)]
    public int WaitingTime;
    
    // 对应的鲜花碎片id
    [ProtoMember(5)]
    public int ShardId;
    
    // 合成花卡所需的碎片数量
    [ProtoMember(6)]
    public int ShardNum;
    
    // 风格类型1温馨2浪漫3清新4甜美5绮梦幻丽6雅韵风致
    [ProtoMember(7)]
    public int StyleType;
    
    // 花的品级（1绿2蓝3紫4红5金6鎏光）
    [ProtoMember(8)]
    public int FlowerQuality;
    
    // 对应的种子id
    [ProtoMember(9)]
    public int SeedId;
    
    // 升级模板id
    [ProtoMember(10)]
    public int LevelMould;
    
    // 竞赛权重
    [ProtoMember(11)]
    public int ClubWeight;
    
    // 培育增加繁荣度
    [ProtoMember(12)]
    public int Prosperity;
  }
}
