//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_island_configConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 地图名字
    [ProtoMember(3)]
    public string Name;
    
    // 地图名字
    [ProtoMember(4)]
    public int[] Progresss;
    
    // 地图名字
    [ProtoMember(5)]
    public ProgressRewardObject[] ProgressRewards;
    
    // 上一个花屿id
    [ProtoMember(6)]
    public int PreviousId;
  }
}
