//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_ikebana_vaseConfig {
    
    // 花瓶ID
    [ProtoMember(1)]
    public int VaseId;
    
    // 花瓶等级
    [ProtoMember(2)]
    public string Leve;
    
    // 解锁道具
    [ProtoMember(3)]
    public int UnlockProps;
    
    // 分享id
    [ProtoMember(4)]
    public int ShareId;
    
    // 解锁奖励
    [ProtoMember(5)]
    public UnlockRewardObject[] UnlockRewards;
    
    // 集齐奖励
    [ProtoMember(6)]
    public GatherRewardObject[] GatherRewards;
    
    // 品质
    [ProtoMember(7)]
    public int VaseQuality;
    
    // 获得花瓶增加繁荣度
    [ProtoMember(8)]
    public int Prosperity;
  }
}
