//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_island_eventConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 事件类型。
    //1为直接领奖励
    // 2为有选项选择的事件
    [ProtoMember(2)]
    public int EventType;
    
    // 事件名字
    [ProtoMember(3)]
    public string EventName;
    
    // 事件内容
    [ProtoMember(4)]
    public string EventDesc;
    
    // 两个选项的文本内容
    //用#号隔开
    [ProtoMember(5)]
    public string EventChoose;
    
    // 类型为1的事件奖励
    [ProtoMember(6)]
    public EventRewardObject[] EventRewards;
    
    // 类型为2的事件
    //选第1个选项的奖励
    [ProtoMember(7)]
    public EventChooseReward1Object[] EventChooseReward1s;
    
    // 类型为2的事件
    //选第2个选项的奖励
    [ProtoMember(8)]
    public EventChooseReward2Object[] EventChooseReward2s;
  }
}
