//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_island_tourConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 每分钟金币产出数量
    [ProtoMember(2)]
    public int GoldProduce;
    
    // 每分钟突破道具产出数量
    [ProtoMember(3)]
    public int BreakProduce;
    
    // 产出额外奖励的概率百分比
    [ProtoMember(4)]
    public int ExtraRewardProb;
    
    // 额外奖励池配置
    [ProtoMember(5)]
    public string ExtraRewardPool;
    
    // 产出额外事件的概率百分比
    [ProtoMember(6)]
    public int ExtraEventProb;
    
    // 额外事件奖励提升百分比
    [ProtoMember(7)]
    public int ExtraEventReward;
    
    // 巡游时间上限
    [ProtoMember(8)]
    public int LimitTime;
  }
}
