//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_ikebana_flowerConfig {
    
    // 花的ID
    [ProtoMember(1)]
    public int FlowersDI;
    
    // 鲜花对应槽位[花瓶ID,对应的槽位]
    [ProtoMember(2)]
    public SlotObject[] Slots;
    
    // 解锁奖励
    [ProtoMember(3)]
    public UnlockRewardObject[] UnlockRewards;
  }
}
