//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_ikebana_artConfig {
    
    // 组合ID
    [ProtoMember(1)]
    public int CombinationId;
    
    // 花组合
    [ProtoMember(2)]
    public FlowerCombinationIdObject[] FlowerCombinationIds;
    
    // 出售的金币
    [ProtoMember(3)]
    public int SellPrice;
    
    // 花瓶ID
    [ProtoMember(4)]
    public int VaseId;
    
    // 花艺ID
    [ProtoMember(5)]
    public int IkebanaId;
    
    // 是否参赛
    [ProtoMember(6)]
    public int IsEntry;
    
    // 顾客订单单个奖励
    [ProtoMember(7)]
    public CustomPriceObject[] CustomPrices;
    
    // 概率
    [ProtoMember(8)]
    public int Probability;
    
    // 订单数量
    [ProtoMember(9)]
    public int[] Ratios;
    
    // 订单等级
    [ProtoMember(10)]
    public int Level;
    
    // 是否需要先
    //解锁花瓶
    [ProtoMember(11)]
    public int Vase;
    
    // 增加好感
    [ProtoMember(12)]
    public int LikeExp;
    
    // 增加繁荣度
    [ProtoMember(13)]
    public int Prosperity;
    
    // 花艺经验
    [ProtoMember(14)]
    public int ArtExp;
  }
}
