//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_item_vip_shopConfig {
    
    // 序列
    //id只能顺延，不能插！
    [ProtoMember(1)]
    public int Id;
    
    // 物品ID
    [ProtoMember(2)]
    public long ItemId;
    
    // 物品名称
    [ProtoMember(3)]
    public string ItemName;
    
    // 物品数量
    [ProtoMember(4)]
    public int ItemNum;
    
    // 货币种类（1：钻石、2：好评券）
    [ProtoMember(5)]
    public int PriceType;
    
    // 物品折后价格
    [ProtoMember(6)]
    public int Price;
    
    // 物品类型（0：普通、1：特价、2：每月新花）
    [ProtoMember(7)]
    public int Type;
    
    // 限购次数
    [ProtoMember(8)]
    public int Times;
    
    // 开始时间
    [ProtoMember(9)]
    public int StartTime;
    
    // 结束时间
    [ProtoMember(10)]
    public int EndTime;
    
    // 折扣
    [ProtoMember(11)]
    public int Discount;
  }
}
