//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_island_objectConfig {
    
    // 格子id
    [ProtoMember(1)]
    public int GridId;
    
    // 所属地图id
    [ProtoMember(2)]
    public int MapId;
    
    // 清除消耗
    [ProtoMember(3)]
    public ClearCostObject[] ClearCosts;
    
    // 清除奖励
    [ProtoMember(4)]
    public string ClearReward;
    
    // 物体类型
    [ProtoMember(5)]
    public int ObjectType;
  }
}
