//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_island_stageConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 所属花屿
    [ProtoMember(2)]
    public int IslandId;
    
    // 敌人组
    [ProtoMember(3)]
    public int[] EnemyGroups;
    
    // 通关奖励
    [ProtoMember(4)]
    public StageRewardObject[] StageRewards;
    
    // 背景图
    [ProtoMember(5)]
    public string StageBackground;
    
    // 绘力
    [ProtoMember(6)]
    public int EnemyPower;
    
    // 风格
    [ProtoMember(7)]
    public string EnemyStyle;
    
    // 速度
    [ProtoMember(8)]
    public int Speed;
  }
}
