//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_jumpConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 跳转类型
    [ProtoMember(2)]
    public int JumpType;
    
    // 场景物类型
    [ProtoMember(3)]
    public int SceneObjType;
    
    // 参数
    [ProtoMember(4)]
    public string JumpParam;
    
    // 名字
    [ProtoMember(5)]
    public string JumpName;
  }
}
