//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_loli_exchangeConfig {
    
    // 老奶奶珍藏id
    [ProtoMember(1)]
    public int Id;
    
    // 排列顺序
    [ProtoMember(2)]
    public int Order;
    
    // 1-鲜花
    //2-花瓶
    [ProtoMember(3)]
    public int Type;
    
    // 获得的物品
    [ProtoMember(4)]
    public RewardObject[] Rewards;
    
    // 对应消耗的物品
    [ProtoMember(5)]
    public ExpendObject[] Expends;
    
    // 是否为新花/花瓶
    [ProtoMember(6)]
    public int New;
    
    // 微信开始时间
    [ProtoMember(7)]
    public string WxStartTime;
  }
}
