//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_level_rewardConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 等级
    [ProtoMember(2)]
    public int Level;
    
    // 解锁功能id集合
    [ProtoMember(3)]
    public int[] UnlockSystems;
    
    // 等级奖励
    [ProtoMember(4)]
    public RewardObject[] Rewards;
  }
}
