//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_loli_collectionConfig {
    
    // 老奶奶珍藏id
    [ProtoMember(1)]
    public int Id;
    
    // 排列顺序
    [ProtoMember(2)]
    public int Order;
    
    // 1-鲜花
    //2-花瓶
    [ProtoMember(3)]
    public int Type;
    
    // 任务类型
    [ProtoMember(4)]
    public int TaskType;
    
    // 任务参数
    [ProtoMember(5)]
    public int TypeParam;
    
    // 任务数量
    [ProtoMember(6)]
    public int TaskNum;
    
    // 是否累积
    [ProtoMember(7)]
    public int Ishistory;
    
    // 对应奖励id
    //可配置多个
    [ProtoMember(8)]
    public RewardObject[] Rewards;
    
    // 是否为新花/花瓶
    [ProtoMember(9)]
    public int New;
  }
}
