//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_mallConfig {
    
    // 礼包id
    [ProtoMember(1)]
    public int Id;
    
    // 活动id
    [ProtoMember(2)]
    public int Event;
    
    // 礼包道具
    [ProtoMember(3)]
    public RewardPropsObject[] RewardPropss;
    
    // 礼包名字
    [ProtoMember(4)]
    public string PackName;
    
    // 礼包图标
    [ProtoMember(5)]
    public string PackIcon;
    
    // 限购类型
    [ProtoMember(6)]
    public int LimitType;
    
    // 限购次数
    [ProtoMember(7)]
    public int LimitTimes;
    
    // 购买金额
    [ProtoMember(8)]
    public int Price;
  }
}
