//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_mfriend_configConfig {
    
    // 等级
    [ProtoMember(1)]
    public int Id;
    
    // 升至当前等级所需经验值
    [ProtoMember(2)]
    public int Exp;
    
    // 摸花+1朵的概率
    //百分比
    [ProtoMember(3)]
    public int MoProb;
    
    // 兑换摸花额外增加的次数
    [ProtoMember(4)]
    public int ExtraTime;
    
    // 摸好友异色花额外增加概率
    [ProtoMember(5)]
    public int FairyProb;
  }
}
