//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_map_eventConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 触发的剧情id
    [ProtoMember(2)]
    public int Polt;
    
    // 美术资源
    [ProtoMember(3)]
    public string MapShow;
    
    // 奖励池子
    [ProtoMember(4)]
    public string Reward;
  }
}
