//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_mail_systemConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int MailId;
    
    // 标题1
    [ProtoMember(2)]
    public string Title1;
    
    // 标题2
    [ProtoMember(3)]
    public string Title2;
    
    // 标题3
    [ProtoMember(4)]
    public string Title3;
  }
}
