//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_npc_buffConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 经验
    [ProtoMember(2)]
    public int Exp;
    
    // 加成类型
    [ProtoMember(3)]
    public int[] BuffTypes;
    
    // 人物头像icon
    [ProtoMember(4)]
    public int[] BuffParams;
  }
}
