//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_npcorder_walkConfig {
    
    // 索引ID
    [ProtoMember(1)]
    public int IndexId;
    
    // NPC站位点
    [ProtoMember(2)]
    public float[] PcStation_Xs;
    
    // NPC站位点
    [ProtoMember(3)]
    public float[] NpcStation_Ys;
    
    // 可出现任务的NPC
    [ProtoMember(4)]
    public float[] Standings;
  }
}
