//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_npc_rewardConfig {
    
    // 双主键id
    [ProtoMember(1)]
    public string Id;
    
    // npcid
    [ProtoMember(2)]
    public int NpcId;
    
    // 等级
    [ProtoMember(3)]
    public int Level;
    
    // 升级至当前
    //等级所需经验
    [ProtoMember(4)]
    public int Exp;
    
    // 奖励剧情id
    [ProtoMember(5)]
    public int PoltId;
    
    // 奖励剧情文本
    [ProtoMember(6)]
    public string[] Plots;
    
    // 奖励道具
    [ProtoMember(7)]
    public RewardObject[] Rewards;
  }
}
