//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_npcConfig {
    
    // id
    [ProtoMember(1)]
    public int Id;
    
    // 居民名字
    [ProtoMember(2)]
    public string Name;
    
    // 人物立绘
    [ProtoMember(3)]
    public string Idle;
    
    // 人物头像icon
    [ProtoMember(4)]
    public string Head;
    
    // 喜好礼物合集
    [ProtoMember(5)]
    public int[] LikeGifts;
    
    // 喜好鲜花风格
    [ProtoMember(6)]
    public int[] LikeLabels;
    
    // 居民介绍
    [ProtoMember(7)]
    public string Introduce;
    
    // 性格
    [ProtoMember(8)]
    public string Personality;
    
    // 喜好
    [ProtoMember(9)]
    public string Preference;
    
    // 身份
    [ProtoMember(10)]
    public string Identity;
    
    // npc对话
    [ProtoMember(11)]
    public string[] Tags;
    
    // npc资源
    [ProtoMember(12)]
    public string Resouce;
    
    // 解锁条件
    [ProtoMember(13)]
    public int[] UnlockConditions;
  }
}
