//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_order_levelConfig {
    
    // 等级
    [ProtoMember(1)]
    public int Leve;
    
    // 需求种类概率（一种）
    [ProtoMember(2)]
    public int Probability1;
    
    // 需求种类概率（两种）
    [ProtoMember(3)]
    public int Probability2;
    
    // 需求种类概率（三种）
    [ProtoMember(4)]
    public int Probability3;
    
    // 需求数量（总和）
    [ProtoMember(5)]
    public int Quantity;
    
    // 订单刷新时间
    [ProtoMember(6)]
    public int Time;
  }
}
