//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_paom_configConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // zhid
    [ProtoMember(2)]
    public string Zh;
  }
}
