//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_player_iconConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 道具id
    [ProtoMember(2)]
    public int IconId;
    
    // 是否默认
    [ProtoMember(3)]
    public int IsOwn;
    
    // 繁荣度
    [ProtoMember(4)]
    public int Prosperity;
  }
}
