//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_plot_chapterConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 章名字
    [ProtoMember(2)]
    public string ChapterName;
    
    // 章图标
    [ProtoMember(3)]
    public string ChapterIcon;
    
    // 包含的节
    [ProtoMember(4)]
    public int[] Plots;
    
    // 第X节会有奖励
    [ProtoMember(5)]
    public int[] PlotCosts;
  }
}
