//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_player_levelConfig {
    
    // 升级的目标等级,,需要额外配置一个最高等级+1的数据
    [ProtoMember(1)]
    public int Level;
    
    // 需求的经验值：表示从`level-1`等级升到`level`等级所需要的经验值是多少,为累加值,所以第一行应该从2开始
    [ProtoMember(2)]
    public long Exp;
    
    // 升级发放奖励,格式:{"entityId1":count1,"entityId2":count2,...}
    [ProtoMember(3)]
    public RewardObject[] Rewards;
    
    // 升级解锁功能的icon，填写功能的icon，格式：[id1,id2,...]
    [ProtoMember(4)]
    public string[] UnlockResources;
    
    // 每级攻击值
    [ProtoMember(5)]
    public int Attack;
    
    // 每级生命值
    [ProtoMember(6)]
    public int Hp;
    
    // 每级防御值
    [ProtoMember(7)]
    public int Defense;
    
    // 每级速度值
    [ProtoMember(8)]
    public int Speed;
  }
}
