//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_player_attrsConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int ID;
    
    // 属性名字
    [ProtoMember(2)]
    public string AttributeName;
  }
}
