//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_player_gradeConfig {
    
    // 品阶
    [ProtoMember(1)]
    public int Grade;
    
    // 品阶名字
    [ProtoMember(2)]
    public string Name;
    
    // 升品阶对应的风格值条件
    [ProtoMember(3)]
    public int[] GradeTasks;
    
    // 当前品阶攻击力加成百分比
    [ProtoMember(4)]
    public int Attack;
    
    // 当前品阶攻击力加成百分比
    [ProtoMember(5)]
    public int Hp;
    
    // 当前品阶攻击力加成百分比
    [ProtoMember(6)]
    public int Defense;
    
    // 当前品阶攻击力加成百分比
    [ProtoMember(7)]
    public int Speed;
    
    // 灵墨上限
    [ProtoMember(8)]
    public int InkLimit;
  }
}
