//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_plot_dialogueConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 对话类型
    [ProtoMember(2)]
    public int Type;
    
    // 展示头像
    [ProtoMember(3)]
    public string Icon;
    
    // 左右
    [ProtoMember(4)]
    public int LeftRight;
    
    // 对话文本
    [ProtoMember(5)]
    public string Dialogue;
    
    // 对话文本
    [ProtoMember(6)]
    public string Name;
  }
}
