//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_recharge_giftConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 需求充值数额
    [ProtoMember(2)]
    public int AccumulatedRecharge;
    
    // 获得奖励
    [ProtoMember(3)]
    public RewardObject[] Rewards;
    
    // 品质框
    [ProtoMember(4)]
    public int[] Qualitys;
  }
}
