//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_rob_insetConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 收益加成或衰减
    [ProtoMember(2)]
    public int[] GainsBonuss;
    
    // 对应文字key
    [ProtoMember(3)]
    public string InsetText;
    
    // 对应图片
    [ProtoMember(4)]
    public string Inset;
    
    // 出现权重
    [ProtoMember(5)]
    public int Weights;
  }
}
