//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_rob_othersConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 开宝箱所需的
    //七彩花瓣消耗
    [ProtoMember(2)]
    public PetalConsumeObject[] PetalConsumes;
    
    // 开n次宝箱必出一次幸运
    //3,4,5这样填
    [ProtoMember(3)]
    public int[] FirstRules;
    
    // 每开n次宝箱必出一次幸运。6,7,8这样填
    [ProtoMember(4)]
    public int[] HiddenRules;
    
    // 花农工作结束后所提供的七彩花瓣数量
    [ProtoMember(5)]
    public PetalGainObject[] PetalGains;
    
    // 花农被囚禁的固定时间（秒）
    [ProtoMember(6)]
    public int PrisonTime;
    
    // 保护固定时间（秒）
    //【囚禁时间结束后会获得保护时间】
    [ProtoMember(7)]
    public int GuardTime;
    
    // 解锁第1个牢笼的消耗
    [ProtoMember(8)]
    public UnlockConsume1Object[] UnlockConsume1s;
    
    // 解锁第2个牢笼的消耗
    [ProtoMember(9)]
    public UnlockConsume2Object[] UnlockConsume2s;
    
    // 进行抢夺所需消耗的抢夺令数量
    [ProtoMember(10)]
    public SnatchOrderObject[] SnatchOrders;
    
    // 供购买的护盾数量
    [ProtoMember(11)]
    public ShieldNumObject[] ShieldNums;
    
    // 购买护盾的对应钻石消耗
    [ProtoMember(12)]
    public ShieldCostObject[] ShieldCosts;
    
    // 抓取成功率
    //70=70%
    [ProtoMember(13)]
    public int SuccessRate;
    
    // 抓取结果1-成功
    //标题,文字,配图
    [ProtoMember(14)]
    public string[] RobResult1s;
    
    // 抓取结果2-被盾挡
    //标题,文字,配图
    [ProtoMember(15)]
    public string[] RobResult2s;
    
    // 抓取结果3-概率失败
    //标题,文字,配图
    [ProtoMember(16)]
    public string[] RobResult3s;
    
    // 供购买的抢夺令数量
    [ProtoMember(17)]
    public TokenNumObject[] TokenNums;
    
    // 购买抢夺令的对应钻石消耗
    [ProtoMember(18)]
    public TokenCostObject[] TokenCosts;
    
    // 每日赠送抢夺令的数量
    [ProtoMember(19)]
    public EverydayOrderObject[] EverydayOrders;
    
    // 抓人成功后的分享id
    [ProtoMember(20)]
    public int ShareId;
    
    // 领奖时看视频的视频id
    //视频奖励配置表|ft_video
    [ProtoMember(21)]
    public int VideoGain;
    
    // 抢夺被盾挡住后，给予抢夺者的奖励
    [ProtoMember(22)]
    public CompensationNumObject[] CompensationNums;
  }
}
