//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_rookie_taskConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 所属天数
    [ProtoMember(2)]
    public int DayNum;
    
    // 任务类型
    [ProtoMember(3)]
    public int TaskType;
    
    // 类型参数
    [ProtoMember(4)]
    public int TypeParam;
    
    // 任务参数数量
    [ProtoMember(5)]
    public int TaskNum;
    
    // 任务奖励
    [ProtoMember(6)]
    public RewardObject[] Rewards;
    
    // 积分奖励数量
    [ProtoMember(7)]
    public int ScoreReward;
    
    // 任务描述
    [ProtoMember(8)]
    public string TaskDesc;
    
    // 挑战
    [ProtoMember(9)]
    public int JumpId;
  }
}
