//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_rob_rewardConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 类型
    //1-幸运 2-普通
    [ProtoMember(2)]
    public int Type;
    
    // 对应奖励
    [ProtoMember(3)]
    public RewardObject[] Rewards;
    
    // 顺序权重
    [ProtoMember(4)]
    public int Weights;
  }
}
