//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_rob_buyConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int IndexId;
    
    // 道具类型
    //1空军符2钓鱼竿
    [ProtoMember(2)]
    public int ItemType;
    
    // 道具类型
    //1空军符2钓鱼竿
    [ProtoMember(3)]
    public ItemNumObject[] ItemNums;
    
    // 购买类型
    //1钻石2rmb
    [ProtoMember(4)]
    public int BuyType;
    
    // 购买消耗
    [ProtoMember(5)]
    public int BuyConifg;
    
    // 原价展示
    [ProtoMember(6)]
    public int OriginalPrice;
    
    // 限购配置 0不限购1每日限购2每周限购3永久限购
    [ProtoMember(7)]
    public int[] LimitConfigs;
    
    // 是否需要开通VIP才能购买
    [ProtoMember(8)]
    public int IsVip;
  }
}
