//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_starConfig {
    
    // 双主键
    [ProtoMember(1)]
    public string Id;
    
    // 套装id
    [ProtoMember(2)]
    public int SuitId;
    
    // 星级
    [ProtoMember(3)]
    public int Star;
    
    // 升到当前星级消耗
    [ProtoMember(4)]
    public StarCostObject[] StarCosts;
    
    // 对收集属性加成的额外加成量
    [ProtoMember(5)]
    public string StarCollectAdd;
  }
}
