//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_skillConfig {
    
    // 索引id
    [ProtoMember(1)]
    public long ID;
    
    // 技能名字
    [ProtoMember(2)]
    public string Name;
    
    // 释放条件
    [ProtoMember(3)]
    public int Condition;
    
    // 释放条件对应的参数
    [ProtoMember(4)]
    public int ConditionParam;
    
    // 伤害百分比
    [ProtoMember(5)]
    public int DamagePct;
    
    // buff生效回合
    //1-下一回合生效
    //0-当下回合马上生效
    [ProtoMember(6)]
    public int BufffEffectiveRound;
    
    // buff持续回合
    [ProtoMember(7)]
    public int[] BuffRounds;
    
    // buff的id 对应buff表
    [ProtoMember(8)]
    public int[] BuffIds;
    
    // buff的参数
    //千分比
    [ProtoMember(9)]
    public int[] BuffParams;
    
    // buff目标
    //1自己 2敌方
    [ProtoMember(10)]
    public int[] BuffTargets;
    
    // 技能描述
    [ProtoMember(11)]
    public string Desc;
  }
}
