//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_advanceConfig {
    
    // 双主键
    [ProtoMember(1)]
    public string Id;
    
    // 套装id
    [ProtoMember(2)]
    public int SuitId;
    
    // 进阶等级
    [ProtoMember(3)]
    public int AdvanceLv;
    
    // 消耗对应碎片的数量
    [ProtoMember(4)]
    public int AdvanceCost;
    
    // 对收集属性加成的额外加成量
    [ProtoMember(5)]
    public string AdvanceCollectAdd;
    
    // 对收集属性加成的额外加成量
    [ProtoMember(6)]
    public string AdvanceSuitAdd;
  }
}
