//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_shareConfig {
    
    // 分享id
    [ProtoMember(1)]
    public int Fx_id;
    
    // 类型（1-没有加好友功能；2-有加好友功能）
    [ProtoMember(2)]
    public int Fx_type;
    
    // 文本显示
    //(读语言配置表)
    [ProtoMember(3)]
    public string Fx_title;
    
    // 配图
    [ProtoMember(4)]
    public string Fx_imgurl;
    
    // 分享后立即获得奖励
    //(道具id，数量）
    [ProtoMember(5)]
    public Fx_success1Object[] Fx_success1s;
    
    // 今日（自然日），第几次分享后不再获得success1奖励。
    [ProtoMember(6)]
    public int Fx_success1Times;
    
    // 链接有效时间（秒）
    [ProtoMember(7)]
    public int Fx_validity;
  }
}
