//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_skillConfig {
    
    // 主键
    [ProtoMember(1)]
    public int Id;
    
    // 套装技能
    [ProtoMember(2)]
    public int SkillType;
    
    // 出发概率
    [ProtoMember(3)]
    public int SkillProb;
    
    // 参数配置
    [ProtoMember(4)]
    public int[] SkillConfigs;
    
    // 每日上限
    [ProtoMember(5)]
    public int DayLimit;
  }
}
