//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_shop_storeConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 商品道具配置
    [ProtoMember(2)]
    public ItemIdObject[] ItemIds;
    
    // 购买消耗
    [ProtoMember(3)]
    public PriceObject[] Prices;
    
    // 限购配置 0不限购1每日限购2永久限购
    [ProtoMember(4)]
    public int[] LimitConfigs;
  }
}
