//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_drawConfig {
    
    // 主键
    [ProtoMember(1)]
    public int Id;
    
    // 对应奖池
    [ProtoMember(2)]
    public string DrawPool;
    
    // 每开一次获得的对应积分数
    [ProtoMember(3)]
    public int Score;
  }
}
