//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_dressConfig {
    
    // 衣服道具id
    [ProtoMember(1)]
    public int ClothesId;
    
    // 衣服部位类型 1头发2连衣裙3上装4下装5鞋子6脸部7配件
    [ProtoMember(2)]
    public int Type;
    
    // 衣服部位品质
    [ProtoMember(3)]
    public int Quality;
    
    // 是否默认
    [ProtoMember(4)]
    public int IsDefault;
    
    // 魅力值
    [ProtoMember(5)]
    public int CharmNum;
    
    // 是否为单品
    [ProtoMember(6)]
    public int IsSingle;
    
    // 衣服部位品质
    [ProtoMember(7)]
    public int Prosperity;
  }
}
