//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_backConfig {
    
    // 主键
    [ProtoMember(1)]
    public int Id;
    
    // 品质id
    [ProtoMember(2)]
    public int Quality;
    
    // 属性加成
    [ProtoMember(3)]
    public string AddAtts;
    
    // 攻击特效动画名
    [ProtoMember(4)]
    public string AttackAnimation;
  }
}
