//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_configConfig {
    
    // 主键
    //套装索引id
    [ProtoMember(1)]
    public int Id;
    
    // 套装名字
    [ProtoMember(2)]
    public string Name;
    
    // 品质
    [ProtoMember(3)]
    public int Quality;
    
    // 包含的衣服
    [ProtoMember(4)]
    public int[] ContainDresss;
    
    // 收集数量
    [ProtoMember(5)]
    public int[] CollectNums;
    
    // 套装效果
    //对应加成魅力值
    [ProtoMember(6)]
    public string CollectAdd;
    
    // 特殊套装效果
    [ProtoMember(7)]
    public int SuitSkill;
    
    // 增加的繁荣度数值
    [ProtoMember(8)]
    public string Prosperity;
  }
}
