//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_suit_dRewardConfig {
    
    // 主键
    [ProtoMember(1)]
    public int Id;
    
    // 当前轮次积分要求
    [ProtoMember(2)]
    public string ScoreNum;
    
    // 达到积分要求奖励
    [ProtoMember(3)]
    public ScoreRewardObject[] ScoreRewards;
  }
}
