//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_task_dailyConfig {
    
    // 任务ID
    [ProtoMember(1)]
    public int TaskId;
    
    // 任务类型
    [ProtoMember(2)]
    public int TaskType;
    
    // 类型参数
    [ProtoMember(3)]
    public int TypeParam;
    
    // 所需数量
    [ProtoMember(4)]
    public int[] TaskNums;
    
    // 是否累积
    [ProtoMember(5)]
    public int Ishistory;
    
    // 奖励
    [ProtoMember(6)]
    public RewardObject[] Rewards;
    
    // 固定类型
    [ProtoMember(7)]
    public int Type;
    
    // 标题
    [ProtoMember(8)]
    public string Title;
    
    // 1每日2每周
    [ProtoMember(9)]
    public int DayWeek;
    
    // 描述
    [ProtoMember(10)]
    public string Description;
    
    // 进度值
    [ProtoMember(11)]
    public int Progress;
  }
}
