//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_trimming_configConfig {
    
    // id顺序千万不能改！
    [ProtoMember(1)]
    public int IndexId;
    
    // 物品ID;类型，物品id类型
    [ProtoMember(2)]
    public int[] ItemIds;
    
    // 是否为默认装饰物
    //1-是；0-否
    [ProtoMember(3)]
    public int Default;
    
    // 替换装饰物时的icon显示
    [ProtoMember(4)]
    public string Icon;
    
    // 替换装饰物的名字
    [ProtoMember(5)]
    public string Name;
    
    // 组ID
    [ProtoMember(6)]
    public int GroupId;
    
    // 页签名
    [ProtoMember(7)]
    public string GroupName;
    
    // 购买等级限制
    [ProtoMember(8)]
    public int LimitLv;
    
    // 购买，花等级总和限制
    [ProtoMember(9)]
    public int LimitFlower;
    
    // 购买所需道具
    [ProtoMember(10)]
    public NeedItemObject[] NeedItems;
    
    // 获取途径
    [ProtoMember(11)]
    public string SrcType;
  }
}
