//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_task_mainConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 下一个任务
    [ProtoMember(2)]
    public int NextId;
    
    // 任务描述
    [ProtoMember(3)]
    public string TaskDesc;
    
    // 任务类型
    [ProtoMember(4)]
    public int TaskType;
    
    // 类型参数
    [ProtoMember(5)]
    public int TypeParam;
    
    // 所需数量
    [ProtoMember(6)]
    public int TaskNum;
    
    // 是否累积
    [ProtoMember(7)]
    public int Ishistory;
    
    // 任务奖励
    [ProtoMember(8)]
    public TaskRewardObject[] TaskRewards;
    
    // 完成后触发剧情
    [ProtoMember(9)]
    public int IsPolt;
  }
}
