//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_task_progressConfig {
    
    // 索引id
    [ProtoMember(1)]
    public int Id;
    
    // 1每日2每周
    [ProtoMember(2)]
    public int DayWeek;
    
    // 所需进度值
    [ProtoMember(3)]
    public int ProgressNum;
    
    // 进度对应奖励
    [ProtoMember(4)]
    public ProgressRewardObject[] ProgressRewards;
  }
}
