//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_tudiConfig {
    
    // id
    [ProtoMember(1)]
    public int GridId;
    
    // 解锁等级
    [ProtoMember(2)]
    public int UnlockLv;
    
    // 解锁消耗金币
    [ProtoMember(3)]
    public int UnlockCost;
    
    // 是否默认解锁
    [ProtoMember(4)]
    public int IsDefault;
  }
}
