//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_task_levelConfig {
    
    // 等级
    [ProtoMember(1)]
    public int Level;
    
    // 提升百分比(小数向上取整)
    [ProtoMember(2)]
    public int Percentage;
  }
}
