//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_tour_giftConfig {
    
    // 序号
    [ProtoMember(1)]
    public int Id;
    
    // 礼包ID
    [ProtoMember(2)]
    public int[] GiftIds;
    
    // 花卡ID
    [ProtoMember(3)]
    public int[] FlowerIds;
    
    // 额外奖励内容
    [ProtoMember(4)]
    public RewardIdObject[] RewardIds;
    
    // 替换奖励
    [ProtoMember(5)]
    public ReplaceRewardObject[] ReplaceRewards;
    
    // 微信开始时间
    [ProtoMember(6)]
    public string WeixinStartTime;
  }
}
