//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_videoConfig {
    
    // 分享id
    [ProtoMember(1)]
    public int Sp_id;
    
    // 分组
    [ProtoMember(2)]
    public int Sp_group;
    
    // 玩家等级限制，需>=所填等级
    [ProtoMember(3)]
    public int Sp_lv;
    
    // 视频出现概率100%=100
    [ProtoMember(4)]
    public int Sp_probability;
    
    // 每日最大出现次数
    [ProtoMember(5)]
    public int Sp_limit;
    
    // 视频看完后的奖励
    [ProtoMember(6)]
    public Sp_rewardObject[] Sp_rewards;
    
    // 公会资金获得
    [ProtoMember(7)]
    public int Peraga;
  }
}
