//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Ft_video_orderConfig {
    
    // 订单Id
    [ProtoMember(1)]
    public int Id;
    
    // 开放等级
    [ProtoMember(2)]
    public int Level;
    
    // 完成订单次数出现[完成订单的数量，完成订单的数量]
    [ProtoMember(3)]
    public int[] AmountCompleteds;
    
    // 奖励物品
    [ProtoMember(4)]
    public long RewardProps;
    
    // 随机数量
    [ProtoMember(5)]
    public int[] RandomQuantitys;
    
    // 刷新CD
    [ProtoMember(6)]
    public int CompleteCd;
  }
}
