//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Module_profileConfig {
    
    // 键值
    [ProtoMember(1)]
    public string Key;
    
    // 数据值
    [ProtoMember(2)]
    public string Value;
  }
}
