//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elida.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class Module_item_defConfig {
    
    // 道具定义id
    //部分可公式自动生成
    [ProtoMember(1)]
    public int ItemDefId;
    
    // 道具名称文本id
    //部分可公式自动生成
    [ProtoMember(2)]
    public string Name;
    
    // 道具品质
    //（1绿2蓝3紫4红5金6鎏光）
    [ProtoMember(3)]
    public int Quality;
    
    // 道具的资源id：icon、动画，etc…
    [ProtoMember(4)]
    public string ResourceId;
    
    // 道具大分类2位Id用于大分类道具的统一操作功能
    [ProtoMember(5)]
    public int Category;
    
    // 道具子分类4位Id用于特殊功能物品的类型区分
    [ProtoMember(6)]
    public int Type;
    
    // 道具每个格子的堆叠数量
    [ProtoMember(7)]
    public int StackCount;
    
    // 道具的可互动性：是否可出售
    [ProtoMember(8)]
    public int Binding;
    
    // 拥有上限：玩家拥有该道具的总上限
    [ProtoMember(9)]
    public int OwnLimit;
    
    // 有效期：单位为秒，大于0时表示该道具为时效性道具
    [ProtoMember(10)]
    public int Duration;
    
    // 出售该道具时获得的虚拟货币的id,填entityid
    [ProtoMember(11)]
    public string RecycleId;
    
    // 出售该道具时获得的虚拟货币的数量
    [ProtoMember(12)]
    public int RecycleCount;
    
    // 该道具的行为id：e.g，1表示打开礼盒，etc…
    [ProtoMember(13)]
    public int[] ActionIds;
    
    // 道具描述
    [ProtoMember(14)]
    public string Description;
    
    // 物品来源
    [ProtoMember(15)]
    public string Source;
    
    // 仓库类型id，与物品子类型号一致,表示该物品存放在的仓库类型
    [ProtoMember(16)]
    public int WarehouseId;
    
    // 快速购买时的宝石价格，计算公式：购买数*价格，结果向上取整
    [ProtoMember(17)]
    public float QuickBuyCost;
    
    // 玩家需要达到此等级方可使用此物品(需与建筑表的解锁等级保持一致)
    [ProtoMember(18)]
    public int UnlockLv;
    
    // 对应解锁的花朵
    [ProtoMember(19)]
    public int UnlockFlowerId;
    
    // 有效期（秒）
    [ProtoMember(20)]
    public int Indate;
    
    // 花的美术资源是否调用另一套资源（0不调用，1调用）
    [ProtoMember(21)]
    public int Alter_avatar;
  }
}
